'use client';
import Link from 'next/link';
import Shell from '../../components/Shell';
import {useStore,eur} from '../../lib/store';
import {useState} from 'react';
import {PROJECT_STATUSES} from '../../lib/types';

const fmt=(v?:string)=>v?new Date(v).toLocaleDateString('de-DE'):'offen';
export default function Page(){const {state,add}=useStore();const [f,setF]=useState({customer:'',title:'',value:0,status:'Neue Anfrage',montage:''});return <Shell><div className="pageHead"><div><span className="eyebrow">PROJEKTSTEUERUNG</span><h1>Projekte</h1><p>Bestehende Projektübersicht mit direktem Einstieg in die Projektakte.</p></div></div><div className="panel"><div className="formgrid"><select value={f.customer} onChange={e=>setF({...f,customer:e.target.value})}><option value="">Kunde wählen</option>{state.customers.map(x=><option key={x.id}>{x.name}</option>)}</select><input placeholder="Projekt" value={f.title} onChange={e=>setF({...f,title:e.target.value})}/><input type="number" placeholder="Auftragswert" value={f.value||''} onChange={e=>setF({...f,value:+e.target.value})}/><select value={f.status} onChange={e=>setF({...f,status:e.target.value})}>{PROJECT_STATUSES.map(x=><option key={x}>{x}</option>)}</select><input type="date" value={f.montage} onChange={e=>setF({...f,montage:e.target.value})}/><button onClick={()=>{if(!f.customer||!f.title)return;add('projects',{id:'P-'+Date.now(),...f});setF({customer:'',title:'',value:0,status:'Neue Anfrage',montage:''})}}>Projekt speichern</button></div></div><div className="panel"><div className="tableWrap"><table><thead><tr>{['Projektnummer','Kunde','Projektbezeichnung','Projekttyp','Status','Phase','Priorität','Verantwortlicher','Projektwert','Montagetermin','zuletzt geändert'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{state.projects.map(p=><tr key={p.id} className="clickRow"><td><Link href={`/projekte/${p.id}`}>{p.projectNumber}</Link></td><td>{p.customer}</td><td><Link href={`/projekte/${p.id}`}><b>{p.title}</b></Link></td><td>{p.projectType}</td><td><span className="status blue">{p.status}</span></td><td>{p.phase}</td><td><span className="badge">{p.priority}</span></td><td>{p.responsible||'nicht zugewiesen'}</td><td>{eur(p.value)}</td><td>{fmt(p.montage)}</td><td>{fmt(p.updatedAt)}</td></tr>)}</tbody></table></div></div></Shell>}
