'use client';
import Shell from '../../components/Shell';
import {useMemo,useState} from 'react';
import {useStore} from '../../lib/store';
import {projectTeamAssignments} from '../../lib/models/project-helpers';

const types=['Kundentermin','Aufmaß','Montage','Nacharbeit','Sonstiges'];
function fmt(date:string){return new Intl.DateTimeFormat('de-DE',{weekday:'short',day:'2-digit',month:'2-digit'}).format(new Date(`${date}T00:00:00Z`));}
function monthDays(anchor:string){const d=new Date(`${anchor}T00:00:00Z`);const y=d.getUTCFullYear();const m=d.getUTCMonth();const last=new Date(Date.UTC(y,m+1,0)).getUTCDate();return Array.from({length:last},(_,i)=>`${y}-${String(m+1).padStart(2,'0')}-${String(i+1).padStart(2,'0')}`);}
export default function Page(){
 const {state,add,remove,update}=useStore();
 const [show,setShow]=useState(false);
 const [selected,setSelected]=useState(new Date().toISOString().slice(0,10));
 const [editing,setEditing]=useState<string|null>(null);
 const [f,setF]=useState({title:'',date:selected,type:'Kundentermin'});
 const days=useMemo(()=>monthDays(selected),[selected]);
 const sorted=[...state.appointments].sort((a:any,b:any)=>a.date.localeCompare(b.date));
 const teamEvents=projectTeamAssignments(state.projects,selected).map(assignment=>{const project=state.projects.find(p=>p.id===assignment.projectId);const employee=state.employees.find(e=>e.id===assignment.employeeId);return {id:assignment.id,title:`${project?.title}: ${employee?.name}`,date:selected,type:'Projektzuordnung',readonly:true};});
 const selectedItems=[...sorted.filter((a:any)=>a.date===selected),...teamEvents];
 function openForm(date=selected,id?:string){const existing=id?state.appointments.find((a:any)=>a.id===id):null;setEditing(id||null);setF(existing?{title:existing.title,date:existing.date,type:existing.type}:{title:'',date,type:'Kundentermin'});setShow(true);}
 function save(){if(!f.title.trim())return; if(editing){update('appointments',editing,{id:editing,...f});}else{add('appointments',{id:'KA'+Date.now(),...f});}setSelected(f.date);setShow(false);setEditing(null);setF({...f,title:''});}
 return <Shell><div className="pageHead"><div><p className="eyebrow">TERMINPLANUNG</p><span className="prepBadge">In Vorbereitung</span><h1>Kalender</h1><p>Responsive Monats-, Tages- und Listenansicht mit vollständig verdrahteten Dialogen.</p></div><button className="primary" onClick={()=>openForm()}>+ Termin</button></div>
 <section className="calendarShell"><article className="panel calendarBoard"><div className="panelHead"><h2>{new Intl.DateTimeFormat('de-DE',{month:'long',year:'numeric'}).format(new Date(`${selected}T00:00:00Z`))}</h2><input type="month" value={selected.slice(0,7)} onChange={e=>setSelected(`${e.target.value}-01`)}/></div><div className="calendarGrid">{days.map(d=>{const direct=projectTeamAssignments(state.projects,d).map(a=>({id:a.id,title:`${state.projects.find(p=>p.id===a.projectId)?.title}: ${state.employees.find(e=>e.id===a.employeeId)?.name}`}));const items=[...sorted.filter((a:any)=>a.date===d),...direct];return <button className={`calendarDay ${d===selected?'active':''}`} key={d} onClick={()=>setSelected(d)} onDoubleClick={()=>openForm(d)}><b>{fmt(d)}</b>{items.slice(0,3).map((a:any)=><span className="calendarEvent" key={a.id}>{a.title}</span>)}{items.length>3&&<small>+{items.length-3} weitere</small>}</button>})}</div></article>
 <aside className="panel dayAgenda"><h2>{fmt(selected)}</h2><button className="primary wide" onClick={()=>openForm(selected)}>Termin für diesen Tag</button>{selectedItems.map((x:any)=><article className="requestRow" key={x.id}><div><b>{x.title}</b><p>{x.type} · {new Date(`${x.date}T00:00:00Z`).toLocaleDateString('de-DE')}</p></div>{!x.readonly&&<div className="actions"><button className="ghostBtn" onClick={()=>openForm(x.date,x.id)}>Bearbeiten</button><button className="ghost" onClick={()=>remove('appointments',x.id)}>Löschen</button></div>}</article>)}{!selectedItems.length&&<p className="emptyState">Keine Termine. Tippen Sie auf „Termin für diesen Tag“.</p>}</aside></section>
 {show&&<div className="bottomSheet" role="dialog" aria-modal="true" aria-label="Termin bearbeiten"><div><button className="sheetClose" onClick={()=>setShow(false)}>×</button><h2>{editing?'Termin bearbeiten':'Neuer Termin'}</h2><label>Titel<input placeholder="Termin" value={f.title} onChange={e=>setF({...f,title:e.target.value})}/></label><label>Datum<input type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></label><label>Art<select value={f.type} onChange={e=>setF({...f,type:e.target.value})}>{types.map(t=><option key={t}>{t}</option>)}</select></label><div className="actions"><button className="primary" onClick={save}>Speichern</button>{editing&&<button className="ghost" onClick={()=>{remove('appointments',editing);setShow(false);}}>Löschen</button>}<button className="ghostBtn" onClick={()=>setShow(false)}>Abbrechen</button></div></div></div>}
 <article className="panel tableWrap"><table><thead><tr><th>Datum</th><th>Termin</th><th>Art</th><th>Aktionen</th></tr></thead><tbody>{sorted.map((x:any)=><tr key={x.id}><td>{new Date(`${x.date}T00:00:00Z`).toLocaleDateString('de-DE')}</td><td><b>{x.title}</b></td><td><span className="status blue">{x.type}</span></td><td><button className="ghostBtn" onClick={()=>openForm(x.date,x.id)}>Bearbeiten</button></td></tr>)}</tbody></table></article></Shell>;
}
