const Module=require('node:module');
const ts=require('typescript');
require.extensions['.ts']=(module,filename)=>{const source=require('fs').readFileSync(filename,'utf8');const output=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText;module._compile(output,filename);};
const test=require('node:test');
const assert=require('node:assert/strict');
const f=require('../lib/models/finance.ts');
const baseExt={provider:'Lexoffice',recorded:false};
function out(id='O1',gross=1190){return {id,externalInvoiceNumber:'LX-1',customerName:'Kunde',projectId:'P1',invoiceType:'Schlussrechnung',invoiceDate:'2026-07-01',serviceDate:'2026-07-01',dueDate:'2026-07-10',netAmount:f.money(1000),vatAmount:f.money(190),grossAmount:f.money(gross),vatRate:19,paidAmount:f.money(0),openAmount:f.money(gross),paymentStatus:'Offen',invoiceStatus:'Versendet',paymentTerms:'14 Tage',externalAccounting:baseExt,documentIds:['D1'],internalNote:'',createdAt:'',updatedAt:''};}
function inc(id='I1'){return {id,supplierName:'Lieferant',projectId:'P1',externalInvoiceNumber:'ER-1',invoiceDate:'2026-07-01',serviceDate:'2026-07-01',receivedDate:'2026-07-02',dueDate:'2026-07-20',netAmount:f.money(500),vatAmount:f.money(95),grossAmount:f.money(595),vatRate:19,costCategory:'Projektmaterial',paymentStatus:'Offen',reviewStatus:'Neu',paidAmount:f.money(0),openAmount:f.money(595),externalAccounting:{provider:'DATEV',recorded:false},documentIds:['D2'],internalNote:'',createdAt:'',updatedAt:''};}
const pay=(invoiceId,amount,dir='Ausgang')=>({id:`P-${amount}`,invoiceDirection:dir,invoiceId,projectId:'P1',paymentDate:'2026-07-03',amount:f.money(amount),method:'Überweisung',reference:'R',purpose:'Z',note:'',recordedBy:'ADMIN',createdAt:''});

test('manual outgoing invoice supports partial and full payments, open amount and overdue status',()=>{let i=f.updateOutgoingInvoicePayment(out(),[pay('O1',400)],new Date('2026-07-05'));assert.equal(i.paymentStatus,'Teilweise bezahlt');assert.equal(i.openAmount.cents,79000);i=f.updateOutgoingInvoicePayment(out(),[pay('O1',1190)],new Date('2026-07-05'));assert.equal(i.paymentStatus,'Bezahlt');i=f.updateOutgoingInvoicePayment(out(),[],new Date('2026-07-22'));assert.equal(i.paymentStatus,'Überfällig');});
test('manual incoming invoice, supplier duplicate and liability open item work',()=>{const i=f.updateIncomingInvoicePayment(inc(),[pay('I1',100,'Eingang')],new Date('2026-07-22'));assert.equal(i.paymentStatus,'Teilweise bezahlt');assert.equal(i.openAmount.cents,49500);assert.equal(f.detectIncomingDuplicate(inc('I2'),[inc('I1')]),true);const ops=f.createOpenItems([], [i], new Date('2026-07-22'));assert.equal(ops[0].direction,'Verbindlichkeit');});
test('simple invoice partial payments calculate paid amount, open amount and status',()=>{const invoice={net:1000,vatRate:19,due:'2026-08-01',status:'Offen',payments:[{amount:400}]};assert.equal(f.simpleInvoiceGross(invoice),1190);assert.equal(f.simpleInvoicePaid(invoice),400);assert.equal(f.simpleInvoiceOpen(invoice),790);assert.equal(f.simpleInvoicePaymentStatus(invoice,new Date('2026-07-22')),'Teilweise bezahlt');assert.equal(f.simpleInvoicePaymentStatus({...invoice,payments:[{amount:1190}]},new Date('2026-07-22')),'Bezahlt');});
test('overpayment, cancellation status, credit memo and project linkage are calculated',()=>{assert.equal(f.hasOverpayment(out(),[pay('O1',1200)],'O1'),true);const cancelled=f.updateOutgoingInvoicePayment({...out(),invoiceStatus:'Storniert'},[],new Date('2026-07-22'));assert.equal(cancelled.paymentStatus,'Ausgebucht');const credit={...out('G1'),invoiceType:'Gutschrift',netAmount:f.money(100),vatAmount:f.money(19),grossAmount:f.money(119)};const p=f.projectFinance('P1',[out(),credit],[inc()],[pay('O1',100),pay('I1',50,'Eingang')]);assert.equal(p.projectRevenue.cents,90000);assert.equal(p.projectCosts.cents,50000);assert.equal(p.preliminaryContributionMargin.cents,40000);});
test('document assignment/versioning and recurring tax dates work',()=>{const doc={id:'D2',category:'Ausgangsrechnungen',fileName:'r.pdf',fileType:'application/pdf',fileSize:1,storagePath:'/d/r.pdf',projectId:'P1',invoiceId:'O1',description:'',tags:[],documentDate:'2026-07-01',uploadedBy:'ADMIN',uploadedAt:'',version:1,archived:false};assert.equal(f.nextDocumentVersion({...doc,id:'D3'},[doc]).version,2);const entries=f.recurringTaxEntries({id:'T',type:'Umsatzsteuerzahlung',title:'',period:'2026-07',dueDate:'2026-08-10',status:'Offen',reminderDate:'2026-08-03',documentIds:[],note:'',recurring:true,recurrenceRule:'MONTHLY',createdAt:'',updatedAt:''},3);assert.deepEqual(entries.map(e=>e.dueDate),['2026-08-10','2026-09-10','2026-10-10']);});
test('vat and input tax overview excludes cancelled invoice and lists missing marks',()=>{const cancelled={...out('S'),invoiceStatus:'Storniert',documentIds:[],externalAccounting:{provider:'Lexoffice',recorded:false}};const v=f.vatSummary([out(),cancelled],[{...inc(),documentIds:[]}],'2026-07-01','2026-07-31');assert.equal(v.outputVat.cents,19000);assert.equal(v.inputVat.cents,9500);assert.ok(v.provisionalNotice.includes('Vorläufige'));assert.ok(v.invoicesWithoutDocument.includes('I1'));});
test('csv import preview, duplicate recognition, admin permission and employee block',()=>{const mapping={id:'M',target:'outgoingInvoices',columns:{externalInvoiceNumber:'Rechnungsnummer',customerName:'Kunde'},createdAt:''};const r=f.importCsv('Rechnungsnummer;Kunde\nR1;Kunde\nR2;Kunde',mapping,new Set(['R1|Kunde']));assert.equal(r.imported,1);assert.equal(r.duplicates.length,1);assert.equal(f.canAccessFinance({role:'ADMIN'}),true);assert.throws(()=>f.assertFinanceAccess({role:'MITARBEITER'}));});
