const Module=require('node:module');
const ts=require('typescript');
require.extensions['.ts']=(module,filename)=>{const source=require('fs').readFileSync(filename,'utf8');const output=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText;module._compile(output,filename);};
const test=require('node:test');
const assert=require('node:assert/strict');
const ops=require('../lib/models/operations.ts');

test('employee app splits today upcoming and past construction sites',()=>{const projects=[{id:'P1',plannedInstallationDate:'2026-07-22'},{id:'P2',plannedInstallationDate:'2026-07-30'},{id:'P3',plannedInstallationDate:'2026-07-01'}];const assignments=[{projectId:'P1',employeeId:'E1',date:'2026-07-22'},{projectId:'P2',employeeId:'E1',date:'2026-07-30'},{projectId:'P3',employeeId:'E1',date:'2026-07-01'}];const sections=ops.employeeProjectSections(projects,assignments,'E1','2026-07-22');assert.deepEqual(sections.today.map(p=>p.id),['P1']);assert.deepEqual(sections.upcoming.map(p=>p.id),['P2']);assert.deepEqual(sections.past.map(p=>p.id),['P3']);});

test('employee history returns own hours messages and images',()=>{const work=[{employeeId:'E1',projectId:'P1',startTime:'08:00',endTime:'12:00',breakMinutes:0,travelMinutes:0}];const messages=[{projectId:'P1',createdBy:'E1',images:['a.jpg'],title:'Mangel'},{projectId:'P1',createdBy:'E2',images:['b.jpg'],title:'Fremd'}];const history=ops.employeeProjectHistory('P1','E1',work,messages);assert.equal(history.hours,4);assert.deepEqual(history.images,['a.jpg']);assert.equal(history.messages.length,1);});

test('work time supports start break end day week and project totals',()=>{const base={id:'WT',employeeId:'E1',projectId:'P1',constructionSite:'Site',date:'2026-07-22',travelMinutes:0,activity:'Montage',note:''};const started=ops.startWorkTime(base,'08:00',new Date('2026-07-22T08:00:00Z'));const paused=ops.addBreak(started,30);const ended=ops.endWorkTime(paused,'16:00');assert.equal(ended.netWorkMinutes,450);assert.equal(ops.workHours([ended]),7.5);assert.equal(ops.workHoursByWeek([ended],'E1','2026-07-20'),7.5);assert.equal(ops.workHoursByProject([ended],'P1'),7.5);});

test('unified purchase list groups same article across projects with source breakdown',()=>{const items=['A','B','C'].map((project,index)=>({id:project,article:'Schraube 6x80',unit:'Stück',quantity:[20,40,15][index],priority:'Normal',note:'',category:'Schrauben',description:'',source:'Baustellenmeldung',createdBy:'U',images:[],status:'Offen',suggestedOrderRoute:'bestehendes Einkaufsmodul',createdAt:'',updatedAt:'',projectId:project,constructionSite:`Projekt ${project}`}));const grouped=ops.groupPurchaseListItems(items);assert.equal(grouped.length,1);assert.equal(grouped[0].quantity,75);assert.equal(grouped[0].groupedSources.length,3);});

test('defective and lost tools can be moved into purchase list',()=>{const tool={id:'T1',name:'Bohrhammer',manufacturer:'Demo',model:'X',serialNumber:'S',category:'Werkzeug',status:'Defekt',storageLocation:'Lager',images:[],notes:'Getriebe defekt',active:true};const item=ops.toolPurchaseListItem(tool,'ADMIN');assert.equal(item.source,'Werkzeug');assert.equal(item.category,'Werkzeug');assert.equal(item.article,'Bohrhammer');});

test('vehicle warnings and dashboard counters cover operations KPIs',()=>{const vehicles=[{licensePlate:'KA',tuvValidUntil:'2026-08-01',mileage:9900,nextServiceMileage:10000,status:'Verfügbar'}];assert.ok(ops.vehicleReminders(vehicles[0],new Date('2026-07-22')).includes('TÜV in 30 Tagen fällig'));const metrics=ops.dashboardOperationsMetrics([{category:'Material fehlt',status:'Neu',title:'Material fehlt'},{category:'Werkzeug defekt',status:'Neu',title:'Bohrer'}],vehicles,[{date:'2026-07-22',projectId:'P1',employeeId:'E1'}],[{id:'P2',status:'Nacharbeit'}],'2026-07-22');assert.equal(metrics.todaysSites,1);assert.equal(metrics.openToolMessages,1);assert.equal(metrics.openRework,1);});
