const Module=require('node:module');
const ts=require('typescript');
require.extensions['.ts']=(module,filename)=>{const source=require('fs').readFileSync(filename,'utf8');const output=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText;module._compile(output,filename);};
const test=require('node:test');
const assert=require('node:assert/strict');
const ops=require('../lib/models/operations.ts');
const permissions=require('../lib/models/permissions.ts');
function emp(id){return {id,name:`M ${id}`,phone:'',email:'',role:'Monteur',active:true,skills:[],driverLicenseClass:'B',assignedVehicleIds:[],currentSiteIds:[],availability:'Verfügbar',vacation:[],sickness:[],notes:''};}

test('supports at least 6 employees and unlimited additional employees',()=>{assert.equal(ops.validateMinimumEmployees([1,2,3,4,5,6].map(emp)),true);assert.equal(ops.validateMinimumEmployees(Array.from({length:25},(_,i)=>emp(i))),true);});
test('assignment supports multiple employees per construction site and restricted project visibility',()=>{const projects=[{id:'P1',assignedEmployeeIds:[]},{id:'P2',assignedEmployeeIds:[]}];const assignments=[{projectId:'P1',employeeId:'E1',date:'2026-07-22'},{projectId:'P1',employeeId:'E2',date:'2026-07-22'}];assert.equal(assignments.filter(a=>a.projectId==='P1').length,2);assert.deepEqual(ops.assignedProjectsForEmployee(projects,assignments,'E1','2026-07-22').map(p=>p.id),['P1']);});
test('work time and pauses are calculated and released entries are locked',()=>{const e={employeeId:'E1',startTime:'08:00',endTime:'16:30',breakMinutes:30,travelMinutes:45,status:'Entwurf'};assert.equal(ops.calculateWorkEntry(e).netWorkMinutes,480);assert.equal(ops.workHours([e]),8);assert.equal(ops.canEmployeeEditTime('E1',{...e,status:'Freigegeben'}),false);});
test('project hours are evaluated',()=>{assert.equal(ops.workHoursByProject([{projectId:'P1',startTime:'08:00',endTime:'10:00',breakMinutes:0,travelMinutes:0},{projectId:'P2',startTime:'08:00',endTime:'12:00',breakMinutes:0,travelMinutes:0}], 'P1'),2);});
test('site material categories cover screws silicone sealing tape and tools',()=>{for(const category of ['Schrauben fehlen','Silikon fehlt','Dichtband fehlt','Werkzeug defekt','Werkzeug fehlt','Fahrzeugproblem']) assert.ok(category.length>0);});
test('purchase list groups same articles and creates draft through existing purchasing module shape',()=>{const items=[{id:'A',article:'Silikon',unit:'Stk.',quantity:2,priority:'Normal',note:'',category:'Silikon',description:'',source:'Manuell',createdBy:'U',images:[],status:'Offen',suggestedOrderRoute:'bestehendes Einkaufsmodul',createdAt:'',updatedAt:''},{id:'B',article:'silikon',unit:'Stk.',quantity:3,priority:'Dringend',note:'',category:'Silikon',description:'',source:'Baustellenmeldung',createdBy:'U',images:[],status:'Offen',suggestedOrderRoute:'bestehendes Einkaufsmodul',createdAt:'',updatedAt:''}];const grouped=ops.groupPurchaseListItems(items);assert.equal(grouped.length,1);assert.equal(grouped[0].quantity,5);const order=ops.createPurchaseOrderDraftFromList(grouped,'L1','Lieferant',[]);assert.equal(order.status,'Entwurf');assert.equal(order.items[0].name,'Silikon');});
test('status synchronization links purchase list with order and delivery',()=>{const item={id:'I',status:'Offen'};assert.equal(ops.syncPurchaseListStatus(item,{id:'BE1',status:'Geliefert',updatedAt:'now'}).status,'Geliefert');});
test('minimum stock suggests purchase but does not order automatically',()=>{const item={id:'INV1',articleName:'Dichtband',category:'Dichtband',unit:'Rolle',currentStock:1,minimumStock:5,targetStock:10,active:true};const suggestion=ops.suggestInventoryPurchase(item,'ADMIN');assert.equal(suggestion.quantity,9);assert.equal(suggestion.status,'Offen');});
test('accepted offer creates material requirement draft',()=>{const req=ops.materialRequirementsFromAcceptedOffer({id:'O1',status:'Gewonnen',items:[{id:'P',name:'Markise',description:'',quantity:1,unit:'Stk.'}]},'P1');assert.equal(req[0].toOrder,1);});
test('vehicle TUV and service warnings are explicit including overdue',()=>{const reminders=ops.vehicleReminders({tuvValidUntil:'2026-01-01',mileage:60000,nextServiceMileage:59000,status:'Gesperrt',licensePlate:'KA'} , new Date('2026-07-22'));assert.ok(reminders.includes('TÜV überfällig'));assert.ok(reminders.includes('Service überfällig'));assert.ok(reminders.includes('Fahrzeug gesperrt'));});
test('employee permissions hide confidential purchase prices and cannot approve purchases',()=>{const user={id:'E1',role:'MITARBEITER',assignedProjectIds:[]};assert.equal(permissions.sanitizePurchaseListItemForUser(user,{estimatedPrice:123}).estimatedPrice,undefined);assert.equal(permissions.canApprovePurchase(user),false);});
test('internal notifications are generated for urgent operations events',()=>{const notes=ops.notificationsForOperations([{priority:'Baustopp',title:'Material fehlt',category:'Material fehlt'}],[{tuvValidUntil:'2026-01-01',mileage:1,status:'Verfügbar',licensePlate:'KA'}],[]);assert.ok(notes.length>=2);});
