'use client';
import Shell from '../../components/Shell';
import {useStore} from '../../lib/store';
import {useState} from 'react';
import {sanitizeProjectForUser} from '../../lib/models/permissions';

export default function EmployeePage(){
 const {state,add}=useStore();
 const user=state.users.find(u=>u.role==='MITARBEITER')||state.users[0];
 const assignedIds=new Set([...user.assignedProjectIds,...state.projects.filter(p=>p.assignedEmployeeIds?.includes(user.id)).map(p=>p.id)]);
 const assigned=state.projects.filter(p=>assignedIds.has(p.id)).map(p=>sanitizeProjectForUser(user,p));
 const [activeProjectId,setActiveProjectId]=useState(assigned[0]?.id||'');
 const [feedback,setFeedback]=useState('Bereit für Baustellenmeldung, Bilder, Material, Werkzeug, Mangel und Stunden.');
 const [time,setTime]=useState({date:'2026-07-22',startTime:'08:00',endTime:'16:30',breakMinutes:30,travelMinutes:0,note:''});
 const activeProject=assigned.find(p=>p.id===activeProjectId)||assigned[0];
 const createReport=(category:'Material nachbestellen'|'Werkzeug benötigt'|'Mangel'|'Abnahmebilder'|'Zustandsbilder'|'Sonstiges', title:string, project=activeProject)=>{if(!project)return;const now=new Date().toISOString();add('siteReports',{id:`BM-${Date.now()}`,projectId:project.id,constructionSite:`${project.projectAddress.street}, ${project.projectAddress.city}`,createdBy:user.id,assignedTo:project.responsibleAdminId,category,title,description:`${title} durch ${user.name}`,priority:category==='Mangel'?'Wichtig':'Normal',status:'Neu',images:category==='Abnahmebilder'||category==='Zustandsbilder'?[{id:`IMG-${Date.now()}`,fileReference:'/uploads/mobile-demo.jpg',fileName:'mobile-demo.jpg',fileType:'image/jpeg',uploadedAt:now,uploadedBy:user.id,description:title,category:category==='Abnahmebilder'?'Abnahme':'Montagefortschritt'}]:[],createdAt:now,updatedAt:now,comments:[]});setFeedback(`${title} wurde für ${project.projectNumber} gespeichert und ist in der Verwaltung sichtbar.`)};
 const saveHours=()=>{if(!activeProject)return;const start=new Date(`${time.date}T${time.startTime}:00`),end=new Date(`${time.date}T${time.endTime}:00`);const minutes=Math.max(0,Math.round((end.getTime()-start.getTime())/60000)-time.breakMinutes);add('workTimeEntries',{id:`WT-${Date.now()}`,employeeId:user.id,projectId:activeProject.id,constructionSite:`${activeProject.projectAddress.street}, ${activeProject.projectAddress.city}`,date:time.date,startTime:time.startTime,endTime:time.endTime,breakMinutes:time.breakMinutes,netWorkMinutes:minutes,travelMinutes:time.travelMinutes,activity:'Montage',note:time.note,status:'Eingereicht',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});setFeedback('Stundenmeldung gespeichert und in der Verwaltung eingereicht.')};
 const today=new Date().toISOString().slice(0,10);
return <Shell><div className="pageHead mobileHead"><div><p className="eyebrow">MITARBEITER · MOBILE BAUSTELLE</p><h1>Meine Baustellen</h1><p>Preisfreie Ansicht für zugeordnete Projekte, Meldungen, Notizen, Bildreferenzen und Stunden.</p></div><button className="primary" onClick={()=>createReport('Sonstiges','Baustellenmeldung')}>+ Neue Meldung</button></div>
 <section className="employeeGrid"><article className="panel"><h2>Heute</h2>{assigned.filter(p=>p.montage===today||p.plannedInstallationDate===today).map(p=><a className="bigAction" href={`#${p.id}`} key={p.id}>{p.customer}<small>{p.projectAddress.street}, {p.projectAddress.city}</small></a>)}{assigned.filter(p=>p.montage===today||p.plannedInstallationDate===today).length===0&&<p>Keine Baustelle für heute geplant.</p>}</article><article className="panel"><h2>Nächste Baustellen</h2>{assigned.map(p=><a className="bigAction" href={`#${p.id}`} key={p.id}>{p.customer}<small>{p.montage||p.plannedInstallationDate||'Termin offen'} · {p.title}</small></a>)}</article><article className="panel" id="meldungen"><h2>Offene Meldungen</h2>{state.siteReports.filter(r=>r.createdBy===user.id&&r.status!=='Erledigt').map(r=><div className="alertRow" key={r.id}><b>{r.title}</b><span>{r.category} · {r.status}</span></div>)}</article><article className="panel"><h2>Zugeordnete Projekte</h2><label>Projekt wählen<select value={activeProjectId} onChange={e=>setActiveProjectId(e.target.value)}>{assigned.map(p=><option value={p.id} key={p.id}>{p.projectNumber} · {p.customer} · {p.title}</option>)}</select></label><p className="notice">{feedback}</p></article></section>
 {assigned.map(p=><article className="panel" id={p.id} key={p.id}><div className="panelHead"><div><h2>{p.customer}</h2><small>{p.projectAddress.street}, {p.projectAddress.postalCode} {p.projectAddress.city}</small></div><button className="primary" onClick={()=>{setActiveProjectId(p.id);createReport('Zustandsbilder','Bildreferenz speichern',p)}}>Bildreferenz speichern</button></div><p><b>Ansprechpartner:</b> {p.contactPersons[0]?.name||'siehe Projektakte'} · <b>Telefon:</b> {p.contactPersons[0]?.phone||'nicht hinterlegt'}</p><p><b>Montage:</b> {p.montage||'offen'} · <b>Hinweise:</b> {p.installationNotes||'Keine Einkaufs- oder Verkaufspreise in dieser Ansicht.'}</p><div className="quickButtons"><button onClick={()=>{setActiveProjectId(p.id);createReport('Sonstiges','Baustellenmeldung',p)}}>Baustellenmeldung</button><button onClick={()=>{setActiveProjectId(p.id);createReport('Zustandsbilder','Bilder',p)}}>Bilder</button><button onClick={()=>{setActiveProjectId(p.id);createReport('Material nachbestellen','Materialmeldung',p)}}>Materialmeldung</button><button onClick={()=>{setActiveProjectId(p.id);createReport('Werkzeug benötigt','Werkzeugmeldung',p)}}>Werkzeugmeldung</button><button onClick={()=>{setActiveProjectId(p.id);createReport('Mangel','Mangelmeldung',p)}}>Mangelmeldung</button><button onClick={()=>{setActiveProjectId(p.id);createReport('Abnahmebilder','Abnahmebilder',p)}}>Abnahmebilder</button><button onClick={()=>{setActiveProjectId(p.id);document.getElementById('stundenmeldung')?.scrollIntoView({behavior:'smooth'})}}>Stundenmeldung</button></div></article>)}
 <article className="panel employeeForm" id="stundenmeldung"><h2>Stundenmeldung speichern</h2><div className="formGrid"><label>Datum<input type="date" value={time.date} onChange={e=>setTime({...time,date:e.target.value})}/></label><label>Start<input type="time" value={time.startTime} onChange={e=>setTime({...time,startTime:e.target.value})}/></label><label>Ende<input type="time" value={time.endTime} onChange={e=>setTime({...time,endTime:e.target.value})}/></label><label>Pause (Min.)<input type="number" value={time.breakMinutes} onChange={e=>setTime({...time,breakMinutes:Number(e.target.value)})}/></label><label>Anfahrt (Min.)<input type="number" value={time.travelMinutes} onChange={e=>setTime({...time,travelMinutes:Number(e.target.value)})}/></label><label className="full">Notiz<textarea value={time.note} onChange={e=>setTime({...time,note:e.target.value})} placeholder="z. B. Montage abgeschlossen"/></label></div><button className="primary wide" onClick={saveHours}>Stundenmeldung speichern</button></article></Shell>
}
