'use client';
import Link from 'next/link';
import Shell from '../../components/Shell';
import {useStore,eur} from '../../lib/store';
import {createOpenItems, projectFinance, updateIncomingInvoicePayment, updateOutgoingInvoicePayment, vatSummary} from '../../lib/models/finance';
import {downloadCsv,openItemsCsv} from '../../lib/models/dashboard';
const euro=(cents:number)=>eur(cents/100);
export default function Page(){
 const {state}=useStore();
 const exportCsv=()=>downloadCsv(openItemsCsv(state,new Date('2026-07-22')),'kastonia-offene-posten.csv');
 const outgoing=state.outgoingInvoices.map(i=>updateOutgoingInvoicePayment(i,state.invoicePayments,new Date('2026-07-22')));
 const incoming=state.incomingInvoices.map(i=>updateIncomingInvoicePayment(i,state.invoicePayments,new Date('2026-07-22')));
 const openItems=createOpenItems(outgoing,incoming,new Date('2026-07-22'));
 const vat=vatSummary(outgoing,incoming,'2026-07-01','2026-07-31');
 const project=projectFinance('P-003',outgoing,incoming,state.invoicePayments);
 const received=state.invoicePayments.filter(p=>p.invoiceDirection==='Ausgang'&&!p.cancelledAt).reduce((s,p)=>s+p.amount.cents,0);
 const spent=state.invoicePayments.filter(p=>p.invoiceDirection==='Eingang'&&!p.cancelledAt).reduce((s,p)=>s+p.amount.cents,0);
 return <Shell><div className="top"><div><span className="eyebrow">FINANCE CONTROL v1.9</span><h1>Finanzen, Dokumente & Steuerkalender</h1><p>Manuelle Referenzerfassung für Lexoffice/DATEV. Keine rechtsverbindliche Rechnung, keine Steueranmeldung, keine vollständige Finanzbuchhaltung.</p></div></div>
 <div className="kpis"><div><small>Offene Kundenforderungen</small><b>{euro(openItems.filter(o=>o.direction==='Forderung').reduce((s,o)=>s+o.openAmount.cents,0))}</b></div><div><small>Offene Verbindlichkeiten</small><b>{euro(openItems.filter(o=>o.direction==='Verbindlichkeit').reduce((s,o)=>s+o.openAmount.cents,0))}</b></div><div><small>Zahlungseingänge Monat</small><b>{euro(received)}</b></div><div><small>Ausgaben Monat</small><b>{euro(spent)}</b></div><div><small>Vorläufige USt/VSt</small><b>{euro(vat.outputVat.cents)} / {euro(vat.inputVat.cents)}</b></div></div>
 <div className="panel"><h2>Schnellzugriffe</h2><div className="actions"><Link className="primary" href="#ausgang">Ausgangsrechnungen öffnen</Link><Link className="primary" href="#eingang">Eingangsrechnungen öffnen</Link><Link className="primary" href="#offene-posten">Zahlungen prüfen</Link><Link className="primary" href="/daten">Dokument/Backup verwalten</Link><Link className="primary" href="#steuerkalender">Steuertermine öffnen</Link><button onClick={exportCsv}>CSV offene Posten exportieren</button></div><p className="hint">Alle Schnellzugriffe verwenden unmittelbar die Finance-Control-Datensätze. Der CSV-Export erzeugt eine Excel-kompatible UTF-8-Datei aus den aktuell berechneten offenen Posten. Uploads speichern nur Pfad/Metadaten im Datensatz; Dateien werden nicht als Base64 abgelegt.</p></div>
 <div className="grid2"><div className="panel" id="ausgang"><h2>Ausgangsrechnungen (extern erstellt)</h2><table><thead><tr><th>Extern</th><th>Kunde/Projekt</th><th>Art</th><th>Fällig</th><th>Status</th><th>Offen</th><th>Lexoffice/DATEV</th></tr></thead><tbody>{outgoing.map(i=><tr key={i.id}><td>{i.externalInvoiceNumber}</td><td>{i.customerName}<br/><small>{i.projectName}</small></td><td>{i.invoiceType}</td><td>{i.dueDate}</td><td>{i.paymentStatus}</td><td>{euro(i.openAmount.cents)}</td><td>{i.externalAccounting.recorded?'erfasst':'vorbereiten'}</td></tr>)}</tbody></table></div><div className="panel" id="eingang"><h2>Eingangsrechnungen</h2><table><thead><tr><th>Extern</th><th>Lieferant</th><th>Kategorie</th><th>Prüfung</th><th>Fällig</th><th>Offen</th></tr></thead><tbody>{incoming.map(i=><tr key={i.id}><td>{i.externalInvoiceNumber}</td><td>{i.supplierName}</td><td>{i.costCategory}</td><td>{i.reviewStatus}</td><td>{i.dueDate}</td><td>{euro(i.openAmount.cents)}</td></tr>)}</tbody></table></div></div>
 <div className="grid2"><div className="panel" id="offene-posten"><h2>Offene Posten</h2><table><thead><tr><th>Art</th><th>Partner</th><th>Fällig</th><th>Warnstufe</th><th>Offen</th></tr></thead><tbody>{openItems.map(o=><tr key={o.id}><td>{o.direction}</td><td>{o.partnerName}</td><td>{o.dueDate}</td><td>{o.warningLevel}</td><td>{euro(o.openAmount.cents)}</td></tr>)}</tbody></table></div><div className="panel"><h2>Projektakte P-003 · betriebliche Übersicht</h2><div className="kpis"><div><small>Umsatz Projekt</small><b>{euro(project.projectRevenue.cents)}</b></div><div><small>Projektkosten</small><b>{euro(project.projectCosts.cents)}</b></div><div><small>Offene Forderung</small><b>{euro(project.openReceivables.cents)}</b></div><div><small>Offene Verbindlichkeit</small><b>{euro(project.openPayables.cents)}</b></div><div><small>Vorläufiger DB</small><b>{euro(project.preliminaryContributionMargin.cents)}</b></div></div><p className="hint">{project.notice}</p></div></div>
 <div className="grid2"><div className="panel"><h2>Dokumentenmanagement</h2><table><thead><tr><th>Art</th><th>Datei</th><th>Projekt</th><th>Version</th><th>Archiv</th></tr></thead><tbody>{state.documentRecords.map(d=><tr key={d.id}><td>{d.category}</td><td>{d.fileName}<br/><small>{d.storagePath}</small></td><td>{d.projectId}</td><td>{d.version}</td><td>{d.archived?'ja':'nein'}</td></tr>)}</tbody></table></div><div className="panel" id="steuerkalender"><h2>Steuerkalender</h2><table><thead><tr><th>Termin</th><th>Zeitraum</th><th>Fällig</th><th>Status</th><th>Notiz</th></tr></thead><tbody>{state.taxCalendarEntries.map(t=><tr key={t.id}><td>{t.type}<br/><small>{t.title}</small></td><td>{t.period}</td><td>{t.dueDate}</td><td>{t.status}</td><td>{t.note}</td></tr>)}</tbody></table></div></div>
 <div className="panel"><h2>Vorläufige Umsatzsteuerübersicht Juli 2026</h2><p>{vat.provisionalNotice}</p><div className="kpis"><div><small>Umsatzsteuer Ausgang</small><b>{euro(vat.outputVat.cents)}</b></div><div><small>Vorsteuer Eingang</small><b>{euro(vat.inputVat.cents)}</b></div><div><small>Differenz</small><b>{euro(vat.difference.cents)}</b></div><div><small>Ohne Dokument</small><b>{vat.invoicesWithoutDocument.length}</b></div><div><small>Nicht extern markiert</small><b>{vat.invoicesWithoutExternalAccounting.length}</b></div></div></div></Shell>;
}
