export type TimeEntryActivity='Montage'|'Demontage'|'Aufmaß'|'Fundamente'|'Anlieferung'|'Baustellenvorbereitung'|'Nacharbeit'|'Service'|'Reparatur'|'Lager'|'Einkauf'|'Fahrtzeit'|'Büro'|'sonstige Tätigkeit';
export type TimeEntryStatus='Laufend'|'Entwurf'|'Eingereicht'|'Geprüft'|'Korrigiert'|'Freigegeben';
export const INTERNAL_TIME_ACTIVITIES:TimeEntryActivity[]=['Lager','Einkauf','Büro','sonstige Tätigkeit'];
export interface ProjectTimeEntry{ id:string; employeeId:string; projectId?:string; constructionSite?:string; date:string; workStart:string; pauseStart?:string; pauseEnd?:string; workEnd?:string; pauseMinutes:number; calculatedMinutes:number; activity:TimeEntryActivity; description:string; status:TimeEntryStatus; recordedBy:string; createdAt:string; updatedAt:string; changedAfterSubmit:boolean; changeReason?:string; reviewedBy?:string; reviewedAt?:string; }
const toMinutes=(t:string)=>{const [h='0',m='0']=t.split(':');return Number(h)*60+Number(m)};
const duration=(start:string,end?:string)=>{if(!end)return 0;let s=toMinutes(start),e=toMinutes(end);if(e<s)e+=1440;return Math.max(0,e-s)};
export function validateProjectTimeEntry(entry:Pick<ProjectTimeEntry,'projectId'|'activity'>):string[]{return !entry.projectId&&!INTERNAL_TIME_ACTIVITIES.includes(entry.activity)?['Arbeitszeit ohne Projekt ist nur für interne Tätigkeiten erlaubt.']:[];}
export function calculateProjectTimeEntry(entry:ProjectTimeEntry):ProjectTimeEntry{const pause=entry.pauseStart&&entry.pauseEnd?duration(entry.pauseStart,entry.pauseEnd):entry.pauseMinutes;return {...entry,pauseMinutes:Math.max(0,pause),calculatedMinutes:Math.max(0,duration(entry.workStart,entry.workEnd)-Math.max(0,pause))};}
export function startProjectTime(entry:Omit<ProjectTimeEntry,'status'|'createdAt'|'updatedAt'|'calculatedMinutes'|'pauseMinutes'|'changedAfterSubmit'>,now=new Date()):ProjectTimeEntry{const errors=validateProjectTimeEntry(entry);if(errors.length)throw new Error(errors.join(' '));const iso=now.toISOString();return {...entry,status:'Laufend',pauseMinutes:0,calculatedMinutes:0,changedAfterSubmit:false,createdAt:iso,updatedAt:iso};}
export function closeProjectTime(entry:ProjectTimeEntry,workEnd:string,now=new Date()):ProjectTimeEntry{return calculateProjectTimeEntry({...entry,workEnd,status:'Eingereicht',updatedAt:now.toISOString()});}
export function correctProjectTime(entry:ProjectTimeEntry,patch:Partial<ProjectTimeEntry>,adminId:string,reason:string,now=new Date()):ProjectTimeEntry{if(!reason.trim())throw new Error('Korrekturgrund erforderlich.');return calculateProjectTimeEntry({...entry,...patch,status:'Korrigiert',changedAfterSubmit:true,changeReason:reason,reviewedBy:adminId,reviewedAt:now.toISOString(),updatedAt:now.toISOString()});}
export function releaseProjectTime(entry:ProjectTimeEntry,adminId:string,now=new Date()):ProjectTimeEntry{return {...calculateProjectTimeEntry(entry),status:'Freigegeben',reviewedBy:adminId,reviewedAt:now.toISOString(),updatedAt:now.toISOString()};}
export function hoursByProject(entries:ProjectTimeEntry[],projectId:string){const byEmployee:Record<string,number>={};for(const e of entries.filter(x=>x.projectId===projectId))byEmployee[e.employeeId]=Math.round(((byEmployee[e.employeeId]||0)+calculateProjectTimeEntry(e).calculatedMinutes/60)*100)/100;return {byEmployee,total:Object.values(byEmployee).reduce((a,b)=>Math.round((a+b)*100)/100,0)};}
export function runningTimeEntries(entries:ProjectTimeEntry[]){return entries.filter(e=>e.status==='Laufend'||!e.workEnd)}
export type ReportCategory='Material'|'Werkzeug'|'Fahrzeug'|'Nacharbeit'|'Kundenwunsch'|'Mangel'|'Sicherheit'|'Baustellenproblem'|'Dokument'|'Sonstiges';
export type ReportPriority='Niedrig'|'Normal'|'Hoch'|'Kritisch';export type ReportStatus='Neu'|'Gesehen'|'In Bearbeitung'|'Rückfrage'|'Bestellt'|'Reparatur beauftragt'|'Erledigt'|'Abgelehnt';
export interface EmployeeReport{ id:string; category:ReportCategory; subcategory:string; projectId?:string; constructionSite?:string; employeeId:string; vehicleId?:string; toolId?:string; materialArticleId?:string; title:string; description:string; requestedQuantity?:number; unit?:string; priority:ReportPriority; status:ReportStatus; imageIds:string[]; documentIds:string[]; assignedAdminId?:string; dueDate?:string; createdAt:string; updatedAt:string; completedAt?:string; completionNote?:string; comments:{id:string;authorId:string;text:string;createdAt:string}[]; }
export type PurchaseStatus='Gemeldet'|'Zu prüfen'|'Freigegeben'|'Bestellbereit'|'Bestellt'|'Teilweise geliefert'|'Geliefert'|'Storniert';
export interface PurchaseListItem191{ id:string; article:string; description:string; articleNumber?:string; category:string; quantity:number; unit:string; projectId?:string; source:string; reportId?:string; desiredDeliveryDate?:string; supplierId?:string; priority:ReportPriority; status:PurchaseStatus; orderedAt?:string; orderedBy?:string; receivedQuantity:number; remainingQuantity:number; note:string; }
export function purchaseItemFromMaterialReport(report:EmployeeReport):PurchaseListItem191|undefined{if(report.category!=='Material')return undefined;return {id:`PLI-${report.id}`,article:report.title,description:report.description,category:'Materialmeldung',quantity:report.requestedQuantity||1,unit:report.unit||'Stück',projectId:report.projectId,source:'Mitarbeiter-Materialmeldung',reportId:report.id,priority:report.priority,status:'Gemeldet',receivedQuantity:0,remainingQuantity:report.requestedQuantity||1,note:report.subcategory};}
export function groupPurchase191(items:PurchaseListItem191[]){const m=new Map<string,{article:string;unit:string;total:number;sources:PurchaseListItem191[]}>();for(const i of items){const k=`${i.article.toLowerCase()}|${i.unit.toLowerCase()}`;const cur=m.get(k)||{article:i.article,unit:i.unit,total:0,sources:[]};cur.total+=i.remainingQuantity;cur.sources.push(i);m.set(k,cur)}return Array.from(m.values());}
export type DocumentVisibility='Admin intern'|'Projektteam'|'Mitarbeiter freigegeben'|'Buchhaltung';
export type IncomingDocumentExportStatus='Nicht exportiert'|'Exportbereit'|'Fehlerhaft'|'Exportiert'|'Erneut exportiert'|'Von Buchhaltung verarbeitet';
export interface DocumentRecord191{ id:string; documentType:string; fileName:string; originalFileName:string; fileType:string; fileSize:number; storagePath:string; hash:string; projectId?:string; supplierId?:string; customerId?:string; invoiceId?:string; description:string; tags:string[]; uploadedBy:string; uploadedAt:string; version:number; archived:boolean; visibility:DocumentVisibility; datevExportable:boolean; datevExportStatus:IncomingDocumentExportStatus; }
export const ALLOWED_UPLOAD_TYPES=['application/pdf','image/jpeg','image/png','image/heic','image/heif','image/webp'];
export function validateUpload(file:{name:string;type:string;size:number},projectId?:string,maxSize=15*1024*1024){const errors:string[]=[];if(!ALLOWED_UPLOAD_TYPES.includes(file.type))errors.push('nicht erlaubter Dateityp');if(file.size>maxSize)errors.push('Datei zu groß');if(!projectId)errors.push('fehlender Projektbezug');return errors;}
export interface IncomingDocument{ id:string; type:'Eingangsrechnung'|'Barbeleg'|'Kartenbeleg'|'Tankbeleg'|'Gutschrift'|'Kleinbeleg'|'sonstiger Kostenbeleg'; supplierName:string; projectId?:string; externalNumber?:string; invoiceDate:string; serviceDate?:string; receivedDate:string; dueDate?:string; netCents:number; vatCents:number; grossCents:number; vatRate:number; costCategory:string; paymentMethod:string; paymentStatus:'Offen'|'Teilweise bezahlt'|'Bezahlt'|'Überfällig'; reviewStatus:'Neu'|'Zu prüfen'|'Geprüft'|'Freigegeben'|'Abgelehnt'; documentId?:string; note:string; exportable:boolean; exportStatus:IncomingDocumentExportStatus; exportDate?:string; exportId?:string; processedByAccounting:boolean; externalAccountingReference?:string; }
export interface OutgoingInvoiceReference191{ id:string; externalInvoiceNumber:string; customerName:string; projectId:string; invoiceType:'Abschlagsrechnung'|'Teilrechnung'|'Schlussrechnung'|'Gutschrift'|'Stornorechnung'|'Sonstige'; invoiceDate:string; grossCents:number; paidCents:number; paymentStatus:'Offen'|'Teilweise bezahlt'|'Bezahlt'|'Überfällig'|'Storniert'; }
export interface InvoicePayment191{ id:string; direction:'Ausgang'|'Eingang'; invoiceId:string; projectId?:string; paymentDate:string; amountCents:number; method:string; reference:string; purpose:string; note:string; recordedBy:string; createdAt:string; cancelledAt?:string; }
export function remainingCents(grossCents:number,payments:InvoicePayment191[],invoiceId:string){return grossCents-payments.filter(p=>p.invoiceId===invoiceId&&!p.cancelledAt).reduce((a,p)=>a+p.amountCents,0)}
export function detectOverpayment(grossCents:number,payments:InvoicePayment191[],invoiceId:string){return remainingCents(grossCents,payments,invoiceId)<0}
export function validateIncomingForExport(doc:IncomingDocument){const errors:string[]=[];if(!doc.supplierName)errors.push('Lieferant fehlt');if(!doc.externalNumber)errors.push('Belegnummer fehlt');if(!doc.documentId)errors.push('Dokument fehlt');if(doc.grossCents<=0)errors.push('Bruttobetrag fehlt');return errors;}
export class IncomingDocumentCsvExportProvider{createCsv(docs:IncomingDocument[]){const header='interne_id;belegart;lieferant;belegnummer;rechnungsdatum;leistungsdatum;zahlungsdatum;netto;steuer;brutto;steuersatz;kostenkategorie;zahlungsart;projekt;dokument;notiz;externe_referenz';const rows=docs.map(d=>[d.id,d.type,d.supplierName,d.externalNumber||'',d.invoiceDate,d.serviceDate||'', '',d.netCents/100,d.vatCents/100,d.grossCents/100,d.vatRate,d.costCategory,d.paymentMethod,d.projectId||'',d.documentId||'',d.note,d.externalAccountingReference||''].join(';'));return [header,...rows].join('\n');}}
export class DatevDocumentPackageProvider{validate(docs:IncomingDocument[]){return docs.map(d=>({id:d.id,errors:validateIncomingForExport(d)})).filter(r=>r.errors.length>0)}createPackageName(period:string){return `DATEV-Export-${period}.zip`;}}
export class GenericAccountingPackageProvider{summarize(docs:IncomingDocument[]){return {count:docs.length,netCents:docs.reduce((a,d)=>a+d.netCents,0),vatCents:docs.reduce((a,d)=>a+d.vatCents,0),grossCents:docs.reduce((a,d)=>a+d.grossCents,0),notice:'Strukturierte Übergabe an die Buchhaltung; kein zertifizierter DATEV-Import und keine API-Übertragung.'};}}
export function preliminaryVatSummary(outgoing:OutgoingInvoiceReference191[],incoming:IncomingDocument[]){const output=outgoing.reduce((a,i)=>a+(i.invoiceType==='Gutschrift'||i.invoiceType==='Stornorechnung'?-1:1)*Math.round(i.grossCents*19/119),0);const input=incoming.reduce((a,i)=>a+(i.type==='Gutschrift'?-1:1)*i.vatCents,0);return {outputVatCents:output,inputVatCents:input,differenceCents:output-input,notice:'Vorläufige betriebliche Übersicht; Lexoffice beziehungsweise DATEV bleibt maßgeblich, keine Steueranmeldung.'};}
export function employeeCanReadProjectData(user:{role:string;id:string;assignedProjectIds:string[]},projectId:string){return user.role==='ADMIN'||user.assignedProjectIds.includes(projectId)}
export function assertNoEmployeeFinanceAccess(user:{role:string}){if(user.role!=='ADMIN')throw new Error('Mitarbeiterzugriff auf Finanzdaten, Steuerdaten und DATEV-Export blockiert.');}

export type EmployeeAvailabilityKind='Anwesend'|'Freiwunsch'|'Sonstige Abwesenheit';
export type EmployeeAvailabilityStatus='Eingetragen'|'Beantragt'|'Genehmigt'|'Abgelehnt';
export type EmployeeAvailabilityAbsenceReason='Krankheit'|'Arzttermin'|'Fortbildung'|'Behördentermin'|'Familie'|'Persönlicher Termin'|'Sonstiges';
export interface EmployeeAvailabilityEntry{ id:string; employeeId:string; startDate:string; endDate:string; kind:EmployeeAvailabilityKind; status:EmployeeAvailabilityStatus; reason?:EmployeeAvailabilityAbsenceReason; note?:string; adminComment?:string; createdBy:string; createdAt:string; updatedBy:string; updatedAt:string; decidedBy?:string; decidedAt?:string; }
export interface EmployeeAvailabilityAuditLog{ id:string; availabilityId:string; action:'Erstellt'|'Genehmigt'|'Abgelehnt'|'Geändert'|'Gelöscht'; userId:string; timestamp:string; comment?:string; }
export interface CompanyCalendarBlock{ id:string; date:string; type:'Betriebsferien'|'Gesperrter Samstag'|'Feiertag'; title:string; }
export function dateRange(startDate:string,endDate:string){const result:string[]=[];const start=new Date(`${startDate}T00:00:00Z`);const end=new Date(`${endDate}T00:00:00Z`);for(const d=new Date(start);d<=end;d.setUTCDate(d.getUTCDate()+1))result.push(d.toISOString().slice(0,10));return result;}
export function overlaps(a:{startDate:string;endDate:string},b:{startDate:string;endDate:string}){return a.startDate<=b.endDate&&b.startDate<=a.endDate;}
export function canRequestTimeOff(entries:EmployeeAvailabilityEntry[],employeeId:string,startDate:string,endDate:string){const covered=new Set(entries.filter(e=>e.employeeId===employeeId&&e.kind==='Anwesend'&&e.status==='Eingetragen').flatMap(e=>dateRange(e.startDate,e.endDate)));return dateRange(startDate,endDate).every(day=>covered.has(day));}
export function createAvailabilityEntry(input:Omit<EmployeeAvailabilityEntry,'id'|'status'|'createdAt'|'updatedAt'|'updatedBy'>,existing:EmployeeAvailabilityEntry[],now=new Date()){if(input.kind==='Freiwunsch'&&!canRequestTimeOff(existing,input.employeeId,input.startDate,input.endDate))throw new Error('Freiwunsch kann nur für zuvor als Anwesend eingetragene Tage beantragt werden.');const iso=now.toISOString();return {...input,id:`AV-${now.getTime()}`,status:input.kind==='Freiwunsch'?'Beantragt':'Eingetragen',createdAt:iso,updatedAt:iso,updatedBy:input.createdBy} as EmployeeAvailabilityEntry;}
export function decideAvailability(entry:EmployeeAvailabilityEntry,decision:'Genehmigt'|'Abgelehnt',adminId:string,adminComment:string,now=new Date()){if(entry.kind!=='Freiwunsch')throw new Error('Nur Freiwünsche werden genehmigt oder abgelehnt.');return {...entry,status:decision,adminComment,decidedBy:adminId,decidedAt:now.toISOString(),updatedBy:adminId,updatedAt:now.toISOString()};}
export function employeePlanningAvailability(employeeId:string,date:string,entries:EmployeeAvailabilityEntry[],blocks:CompanyCalendarBlock[],assignments:{employeeId:string;date:string}[]){const block=blocks.find(b=>b.date===date);if(block)return {available:false,level:'blocked',reason:block.type};if(assignments.some(a=>a.employeeId===employeeId&&a.date===date))return {available:false,level:'blocked',reason:'Bereits geplante Baustelle'};const dayEntries=entries.filter(e=>e.employeeId===employeeId&&e.startDate<=date&&e.endDate>=date);if(dayEntries.some(e=>e.kind==='Sonstige Abwesenheit'))return {available:false,level:'blocked',reason:'Sonstige Abwesenheit'};if(dayEntries.some(e=>e.kind==='Freiwunsch'&&e.status==='Genehmigt'))return {available:false,level:'blocked',reason:'Genehmigter Freiwunsch'};if(dayEntries.some(e=>e.kind==='Freiwunsch'&&e.status==='Beantragt'))return {available:true,level:'warning',reason:'Offener Freiwunsch'};if(dayEntries.some(e=>e.kind==='Anwesend'))return {available:true,level:'available',reason:'Anwesend'};return {available:false,level:'blocked',reason:'Keine Anwesenheit eingetragen'};}
