import type { User, UserRole } from '../types';

export const PAYMENT_STATUSES = ['Offen','Teilweise bezahlt','Bezahlt','Überfällig','Ausgebucht'] as const;
export type PaymentStatus = typeof PAYMENT_STATUSES[number];
export const OUTGOING_INVOICE_TYPES = ['Abschlagsrechnung','Teilrechnung','Schlussrechnung','Gutschrift','Stornorechnung','sonstige Ausgangsrechnung'] as const;
export type OutgoingInvoiceType = typeof OUTGOING_INVOICE_TYPES[number];
export const OUTGOING_INVOICE_STATUSES = ['Entwurf extern','Erstellt','Versendet','Storniert'] as const;
export type OutgoingInvoiceStatus = typeof OUTGOING_INVOICE_STATUSES[number];
export const INCOMING_REVIEW_STATUSES = ['Neu','Zu prüfen','Geprüft','Freigegeben','Abgelehnt'] as const;
export type IncomingReviewStatus = typeof INCOMING_REVIEW_STATUSES[number];
export const COST_CATEGORIES = ['Projektmaterial','Befestigungsmaterial','Markisen','Glas','Aluminium','Werkzeug','Fahrzeug','Kraftstoff','Fremdleistung','Montage','Werbung','Büro','Software','Telefon und Internet','Versicherung','Miete','Reisekosten','Steuerberatung','Gebühren','Sonstiges'] as const;
export type CostCategory = typeof COST_CATEGORIES[number];
export const PAYMENT_METHODS = ['Überweisung','Barzahlung','Kartenzahlung','Lastschrift','Verrechnung','Sonstiges'] as const;
export type PaymentMethod = typeof PAYMENT_METHODS[number];
export const DOCUMENT_CATEGORIES = ['Angebote','Auftragsbestätigungen','Ausgangsrechnungen','Eingangsrechnungen','Gutschriften','Bestellungen','Lieferscheine','Lieferantenangebote','Verträge','Aufmaßunterlagen','technische Zeichnungen','Montagepläne','Baustellenbilder','Zustandsbilder','Abnahmebilder','Montageprotokolle','Abnahmeprotokolle','Fahrzeugdokumente','TÜV-Berichte','Werkzeugdokumente','Steuerunterlagen','sonstige Dokumente'] as const;
export type DocumentCategory = typeof DOCUMENT_CATEGORIES[number];
export const TAX_CALENDAR_TYPES = ['Umsatzsteuervoranmeldung','Umsatzsteuerzahlung','Lohnsteueranmeldung','Lohnsteuerzahlung','Einkommensteuer-Vorauszahlung','Gewerbesteuer-Vorauszahlung','Körperschaftsteuer-Vorauszahlung','Sozialversicherungsbeiträge','Berufsgenossenschaft','Versicherungen','Fahrzeugsteuer','Steuerberater-Unterlagen','Jahresabschluss-Unterlagen','sonstige Abgabe','individueller Termin'] as const;
export type TaxCalendarType = typeof TAX_CALENDAR_TYPES[number];
export const TAX_CALENDAR_STATUSES = ['Offen','Unterlagen fehlen','In Vorbereitung','An Steuerberater übermittelt','Erledigt','Bezahlt','Überfällig','Nicht relevant'] as const;
export type TaxCalendarStatus = typeof TAX_CALENDAR_STATUSES[number];

export interface ExternalAccountingReference { provider:'Lexoffice'|'DATEV'|'Beide'|'Extern'; recorded:boolean; reference?:string; voucherNumber?:string; bookingNote?:string; taxCode?:string; }
export interface MoneyAmount { cents:number; currency:'EUR'; }
export interface OutgoingInvoiceReference { id:string; externalInvoiceNumber:string; customerId?:string; customerName:string; projectId?:string; projectName?:string; offerId?:string; orderId?:string; invoiceType:OutgoingInvoiceType; invoiceDate:string; serviceDate:string; dueDate:string; netAmount:MoneyAmount; vatAmount:MoneyAmount; grossAmount:MoneyAmount; vatRate:number; paidAmount:MoneyAmount; openAmount:MoneyAmount; paymentStatus:PaymentStatus; invoiceStatus:OutgoingInvoiceStatus; paymentTerms:string; cashDiscountDueDate?:string; cashDiscountAmount?:MoneyAmount; externalAccounting:ExternalAccountingReference; documentIds:string[]; internalNote:string; createdAt:string; updatedAt:string; }
export interface IncomingInvoiceReference { id:string; supplierId?:string; supplierName:string; projectId?:string; purchaseOrderId?:string; deliveryId?:string; externalInvoiceNumber:string; invoiceDate:string; serviceDate:string; receivedDate:string; dueDate:string; netAmount:MoneyAmount; vatAmount:MoneyAmount; grossAmount:MoneyAmount; vatRate:number; costCategory:CostCategory; costCenter?:string; paymentStatus:Exclude<PaymentStatus,'Ausgebucht'>; reviewStatus:IncomingReviewStatus; paidAt?:string; paidAmount:MoneyAmount; openAmount:MoneyAmount; externalAccounting:ExternalAccountingReference; documentIds:string[]; internalNote:string; createdAt:string; updatedAt:string; }
export interface InvoicePayment { id:string; invoiceDirection:'Ausgang'|'Eingang'; invoiceId:string; customerId?:string; customerName?:string; supplierId?:string; supplierName?:string; projectId?:string; paymentDate:string; amount:MoneyAmount; method:PaymentMethod; reference:string; purpose:string; note:string; recordedBy:string; createdAt:string; cancelledAt?:string; correctionOfPaymentId?:string; }
export interface OpenItem { id:string; direction:'Forderung'|'Verbindlichkeit'; invoiceId:string; partnerName:string; projectId?:string; dueDate:string; grossAmount:MoneyAmount; paidAmount:MoneyAmount; openAmount:MoneyAmount; paymentStatus:PaymentStatus; daysToDue:number; warningLevel:'in 14 Tagen fällig'|'in 7 Tagen fällig'|'heute fällig'|'überfällig'|'mehr als 30 Tage überfällig'|'keine'; }
export interface DocumentRecord { id:string; category:DocumentCategory; fileName:string; fileType:string; fileSize:number; storagePath:string; customerId?:string; supplierId?:string; projectId?:string; invoiceId?:string; purchaseOrderId?:string; deliveryId?:string; vehicleId?:string; toolId?:string; taxCalendarEntryId?:string; description:string; tags:string[]; documentDate:string; uploadedBy:string; uploadedAt:string; version:number; archived:boolean; previousVersionId?:string; }
export interface TaxCalendarEntry { id:string; type:TaxCalendarType; title:string; period:string; dueDate:string; responsibleUserId?:string; status:TaxCalendarStatus; reminderDate:string; amount?:MoneyAmount; paidAt?:string; documentIds:string[]; note:string; recurring:boolean; recurrenceRule?:string; createdAt:string; updatedAt:string; }
export interface VatSummary { periodStart:string; periodEnd:string; outputVat:MoneyAmount; inputVat:MoneyAmount; difference:MoneyAmount; invoicesWithoutTax:string[]; invoicesWithoutDocument:string[]; invoicesWithoutExternalAccounting:string[]; provisionalNotice:string; }
export interface FinanceDashboardMetric { id:string; label:string; amount?:MoneyAmount; count?:number; severity:'info'|'warning'|'danger'|'success'; }
export interface ImportMapping { id:string; target:'outgoingInvoices'|'incomingInvoices'|'invoicePayments'; columns:Record<string,string>; createdAt:string; }
export interface ImportResult { rows:number; imported:number; duplicates:string[]; errors:{row:number; message:string}[]; preview:Record<string,string>[]; }

export const money=(euro:number):MoneyAmount=>({cents:Math.round(euro*100),currency:'EUR'});
export const addMoney=(items:MoneyAmount[]):MoneyAmount=>({cents:items.reduce((s,m)=>s+m.cents,0),currency:'EUR'});
export const subMoney=(a:MoneyAmount,b:MoneyAmount):MoneyAmount=>({cents:a.cents-b.cents,currency:'EUR'});
export const absMoney=(a:MoneyAmount):MoneyAmount=>({cents:Math.abs(a.cents),currency:'EUR'});
type SimpleInvoicePayment={amount:number};
type SimpleInvoice={net:number;vatRate:number;due?:string;status:string;gross?:number;paidAmount?:number;payments?:SimpleInvoicePayment[]};
export function simpleInvoiceGross(invoice:SimpleInvoice):number{return invoice.gross??invoice.net+(invoice.vatRate<0?0:invoice.net*invoice.vatRate/100);}
export function simpleInvoicePaid(invoice:SimpleInvoice):number{return invoice.payments?.reduce((sum,payment)=>sum+payment.amount,0)??invoice.paidAmount??(invoice.status==='Bezahlt'?simpleInvoiceGross(invoice):0);}
export function simpleInvoiceOpen(invoice:SimpleInvoice):number{return Math.max(0,simpleInvoiceGross(invoice)-simpleInvoicePaid(invoice));}
export function simpleInvoicePaymentStatus(invoice:SimpleInvoice,today=new Date()):PaymentStatus{const gross=simpleInvoiceGross(invoice);const paid=simpleInvoicePaid(invoice);if(paid>=gross)return 'Bezahlt';if(paid>0)return 'Teilweise bezahlt';if(invoice.due&&new Date(`${invoice.due}T23:59:59`)<today)return 'Überfällig';return 'Offen';}
const activePayments=(payments:InvoicePayment[], invoiceId:string)=>payments.filter(p=>p.invoiceId===invoiceId&&!p.cancelledAt);
export function paymentTotal(payments:InvoicePayment[], invoiceId:string):MoneyAmount{return addMoney(activePayments(payments,invoiceId).map(p=>p.amount));}
export function updateOutgoingInvoicePayment(invoice:OutgoingInvoiceReference,payments:InvoicePayment[],today=new Date()):OutgoingInvoiceReference{const paid=paymentTotal(payments,invoice.id);const open=subMoney(invoice.grossAmount,paid);const overdue=open.cents>0&&new Date(invoice.dueDate)<today;const paymentStatus:PaymentStatus=invoice.invoiceStatus==='Storniert'||invoice.invoiceType==='Stornorechnung'?'Ausgebucht':open.cents<=0?'Bezahlt':paid.cents>0?'Teilweise bezahlt':overdue?'Überfällig':'Offen';return {...invoice,paidAmount:paid,openAmount:open.cents<0?money(0):open,paymentStatus};}
export function updateIncomingInvoicePayment(invoice:IncomingInvoiceReference,payments:InvoicePayment[],today=new Date()):IncomingInvoiceReference{const paid=paymentTotal(payments,invoice.id);const open=subMoney(invoice.grossAmount,paid);const overdue=open.cents>0&&new Date(invoice.dueDate)<today;const paymentStatus:IncomingInvoiceReference['paymentStatus']=open.cents<=0?'Bezahlt':paid.cents>0?'Teilweise bezahlt':overdue?'Überfällig':'Offen';return {...invoice,paidAmount:paid,openAmount:open.cents<0?money(0):open,paymentStatus,paidAt:open.cents<=0?activePayments(payments,invoice.id).at(-1)?.paymentDate:invoice.paidAt};}
export function hasOverpayment(invoice:{grossAmount:MoneyAmount},payments:InvoicePayment[],invoiceId:string):boolean{return paymentTotal(payments,invoiceId).cents>invoice.grossAmount.cents;}
function warning(due:string,today:Date):OpenItem['warningLevel']{const d=Math.ceil((new Date(due).getTime()-today.getTime())/86400000);if(d < -30)return 'mehr als 30 Tage überfällig'; if(d<0)return 'überfällig'; if(d===0)return 'heute fällig'; if(d<=7)return 'in 7 Tagen fällig'; if(d<=14)return 'in 14 Tagen fällig'; return 'keine';}
export function createOpenItems(outgoing:OutgoingInvoiceReference[],incoming:IncomingInvoiceReference[],today=new Date()):OpenItem[]{const outs=outgoing.filter(i=>i.openAmount.cents>0&&i.invoiceStatus!=='Storniert').map(i=>({id:`OP-${i.id}`,direction:'Forderung' as const,invoiceId:i.id,partnerName:i.customerName,projectId:i.projectId,dueDate:i.dueDate,grossAmount:i.grossAmount,paidAmount:i.paidAmount,openAmount:i.openAmount,paymentStatus:i.paymentStatus,daysToDue:Math.ceil((new Date(i.dueDate).getTime()-today.getTime())/86400000),warningLevel:warning(i.dueDate,today)}));const ins=incoming.filter(i=>i.openAmount.cents>0).map(i=>({id:`OP-${i.id}`,direction:'Verbindlichkeit' as const,invoiceId:i.id,partnerName:i.supplierName,projectId:i.projectId,dueDate:i.dueDate,grossAmount:i.grossAmount,paidAmount:i.paidAmount,openAmount:i.openAmount,paymentStatus:i.paymentStatus,daysToDue:Math.ceil((new Date(i.dueDate).getTime()-today.getTime())/86400000),warningLevel:warning(i.dueDate,today)}));return [...outs,...ins];}
export function projectFinance(projectId:string,outgoing:OutgoingInvoiceReference[],incoming:IncomingInvoiceReference[],payments:InvoicePayment[]){const out=outgoing.filter(i=>i.projectId===projectId&&i.invoiceStatus!=='Storniert');const inc=incoming.filter(i=>i.projectId===projectId);const revenue=addMoney(out.map(i=>i.invoiceType==='Gutschrift'?{...i.netAmount,cents:-i.netAmount.cents}:i.netAmount));const costs=addMoney(inc.map(i=>i.netAmount));const customerPaid=addMoney(payments.filter(p=>p.projectId===projectId&&p.invoiceDirection==='Ausgang'&&!p.cancelledAt).map(p=>p.amount));const supplierPaid=addMoney(payments.filter(p=>p.projectId===projectId&&p.invoiceDirection==='Eingang'&&!p.cancelledAt).map(p=>p.amount));return {projectRevenue:revenue,customerPayments:customerPaid,projectCosts:costs,openReceivables:subMoney(addMoney(out.map(i=>i.grossAmount)),customerPaid),openPayables:subMoney(addMoney(inc.map(i=>i.grossAmount)),supplierPaid),preliminaryContributionMargin:subMoney(revenue,costs),notice:'Betriebliche Übersicht, keine steuerliche Gewinnermittlung.'};}
export function vatSummary(outgoing:OutgoingInvoiceReference[],incoming:IncomingInvoiceReference[],start:string,end:string):VatSummary{const inRange=(d:string)=>d>=start&&d<=end;const out=outgoing.filter(i=>inRange(i.invoiceDate)&&i.invoiceStatus!=='Storniert');const inn=incoming.filter(i=>inRange(i.invoiceDate));const outputVat=addMoney(out.map(i=>i.invoiceType==='Gutschrift'?{...i.vatAmount,cents:-i.vatAmount.cents}:i.vatAmount));const inputVat=addMoney(inn.map(i=>i.vatAmount));const all=[...out,...inn];return {periodStart:start,periodEnd:end,outputVat,inputVat,difference:subMoney(outputVat,inputVat),invoicesWithoutTax:all.filter(i=>i.vatRate===undefined||i.vatAmount.cents===0).map(i=>i.id),invoicesWithoutDocument:all.filter(i=>i.documentIds.length===0).map(i=>i.id),invoicesWithoutExternalAccounting:all.filter(i=>!i.externalAccounting.recorded).map(i=>i.id),provisionalNotice:'Vorläufige betriebliche Übersicht; Lexoffice/DATEV bleibt maßgeblich, keine Steueranmeldung.'};}
export function detectIncomingDuplicate(candidate:IncomingInvoiceReference,invoices:IncomingInvoiceReference[]):boolean{return invoices.some(i=>i.supplierName===candidate.supplierName&&i.externalInvoiceNumber===candidate.externalInvoiceNumber&&i.grossAmount.cents===candidate.grossAmount.cents&&i.id!==candidate.id);}
export function nextDocumentVersion(doc:DocumentRecord, existing:DocumentRecord[]):DocumentRecord{const same=existing.filter(d=>d.storagePath===doc.storagePath||d.fileName===doc.fileName);const version=Math.max(0,...same.map(d=>d.version))+1;return {...doc,version,previousVersionId:same.at(-1)?.id};}
export function recurringTaxEntries(entry:TaxCalendarEntry,count:number):TaxCalendarEntry[]{if(!entry.recurring||!entry.recurrenceRule)return [entry];const months=entry.recurrenceRule==='MONTHLY'?1:entry.recurrenceRule==='QUARTERLY'?3:12;return Array.from({length:count},(_,i)=>{const due=new Date(entry.dueDate);due.setMonth(due.getMonth()+months*i);return {...entry,id:i===0?entry.id:`${entry.id}-${i+1}`,dueDate:due.toISOString().slice(0,10)};});}
export function canAccessFinance(user:Pick<User,'role'>|{role:UserRole}):boolean{return user.role==='ADMIN';}
export function assertFinanceAccess(user:Pick<User,'role'>|{role:UserRole}):void{if(!canAccessFinance(user))throw new Error('Mitarbeiterzugriff auf Finanz-, Steuer- und OP-Daten blockiert.');}
export function parseCsvPreview(csv:string):Record<string,string>[] {const [head,...rows]=csv.trim().split(/\r?\n/);const headers=head.split(';').map(h=>h.trim());return rows.map(row=>Object.fromEntries(row.split(';').map((v,i)=>[headers[i]||`Spalte ${i+1}`,v.trim()])));}
export function importCsv(csv:string, mapping:ImportMapping, existingKeys:Set<string>):ImportResult{const preview=parseCsvPreview(csv);const duplicates:string[]=[];const errors:{row:number;message:string}[]=[];preview.forEach((row,index)=>{const keyFields=Object.values(mapping.columns).map(source=>row[source]||'').join('|');if(!keyFields)errors.push({row:index+2,message:'Pflichtfelder fehlen'});if(existingKeys.has(keyFields))duplicates.push(keyFields);});return {rows:preview.length,imported:preview.length-duplicates.length-errors.length,duplicates,errors,preview};}
