import type {Offer,OfferCalculation,OfferItem,OfferStatus,Project} from '../types';

export const OFFER_STATUSES: OfferStatus[]=['Entwurf','In Bearbeitung','Versendet','Nachfassen','Gewonnen','Verloren','Storniert'];
export const OFFER_ITEM_TYPES=['Terrassendach','Wintergarten','Lamellendach','Carport','Pergola','Aufdachmarkise','Unterdachmarkise','ZIP','Glasschiebeelemente','LED','Montage','Fundament','Sonderposition','Freitext'] as const;
const round=(n:number)=>Math.round((n+Number.EPSILON)*100)/100;
const safe=(n:number)=>Number.isFinite(n)?n:0;
export function createOfferNumber(existing:Pick<Offer,'offerNumber'|'id'>[],date=new Date()):string{const y=date.getFullYear();const prefix=`AG${y}`;const nums=existing.map(o=>o.offerNumber||o.id).filter(n=>n.startsWith(prefix)).map(n=>Number(n.slice(prefix.length, prefix.length+4))).filter(Number.isFinite);const next=Math.max(0,...nums)+1;return `${prefix}${String(next).padStart(4,'0')}`;}
export function nextOfferVersion(existing:Pick<Offer,'offerNumber'|'version'>[],offerNumber:string):number{return Math.max(0,...existing.filter(o=>o.offerNumber===offerNumber).map(o=>o.version||1))+1;}
export function calculateOfferItem(item:OfferItem):OfferItem{const quantity=safe(item.quantity);const grossVk=safe(item.salesPrice)*quantity;const discountAmount=round(grossVk*(safe(item.discount)/100));const net=round(grossVk-discountAmount);const cost=round(safe(item.purchasePrice)*quantity);const vat=round(net*(safe(item.vatRate)/100));const gross=round(net+vat);const marginAmount=round(net-cost);const marginPercent=net?round((marginAmount/net)*100):0;return {...item,totalNet:net,totalGross:gross,marginAmount,marginPercent};}
export function calculateOffer(items:OfferItem[]):OfferCalculation{const calculated=items.map(calculateOfferItem);const by=(type:string)=>round(calculated.filter(i=>i.type===type).reduce((a,i)=>a+i.totalNet,0));const net=round(calculated.reduce((a,i)=>a+i.totalNet,0));const gross=round(calculated.reduce((a,i)=>a+i.totalGross,0));const vat=round(gross-net);const purchase=round(calculated.reduce((a,i)=>a+safe(i.purchasePrice)*safe(i.quantity),0));const discount=round(items.reduce((a,i)=>a+(safe(i.salesPrice)*safe(i.quantity)*safe(i.discount)/100),0));const marginAmount=round(net-purchase);const marginPercent=net?round((marginAmount/net)*100):0;return {net,gross,vat,discount,material:round(net-by('Montage')-by('Fundament')-by('Sonderposition')-by('Freitext')),assembly:by('Montage'),delivery:0,other:round(by('Fundament')+by('Sonderposition')+by('Freitext')),contributionMargin:marginAmount,marginAmount,marginPercent,projectProfit:marginAmount};}
export function createEmptyOffer(project:Project,existing:Offer[],date=new Date()):Offer{const offerNumber=createOfferNumber(existing,date);const now=date.toISOString();return {id:`${offerNumber}-V1`,offerNumber,version:1,date:now.slice(0,10),status:'Entwurf',customer:project.customer,title:project.title,projectId:project.id,projectNumber:project.projectNumber,editor:project.responsible||'Kastonia Team',items:[],net:0,gross:0,calculation:calculateOffer([]),statusHistory:[{id:`H-${Date.now()}`,date:now,from:'',to:'Entwurf',user:project.responsible||'Kastonia Team',note:'Angebot erstellt'}]};}
export function duplicateOffer(offer:Offer,existing:Offer[],date=new Date()):Offer{const version=nextOfferVersion(existing,offer.offerNumber||offer.id);const calc=calculateOffer(offer.items||[]);return {...offer,id:`${offer.offerNumber}-V${version}`,version,date:date.toISOString().slice(0,10),status:'Entwurf',net:calc.net,gross:calc.gross,calculation:calc,statusHistory:[...(offer.statusHistory||[]),{id:`H-${Date.now()}`,date:date.toISOString(),from:offer.status,to:'Entwurf',user:offer.editor,note:`Version ${version} erstellt`} ]};}
export function changeOfferStatus(offer:Offer,status:OfferStatus,user:string,date=new Date()):Offer{return {...offer,status,statusHistory:[...(offer.statusHistory||[]),{id:`H-${Date.now()}`,date:date.toISOString(),from:offer.status,to:status,user,note:'Status geändert'}]};}
export function summarizeProjectOffers(project:Project,offers:Offer[]){const list=offers.filter(o=>o.projectId===project.id || project.offers.some(po=>po.id===o.id));const current=[...list].sort((a,b)=>(b.date||'').localeCompare(a.date||'')||(b.version||0)-(a.version||0))[0];const won=list.filter(o=>o.status==='Gewonnen').reduce((a,o)=>a+(o.gross||o.net),0);return {lastOffer:current,currentOffer:current,count:list.length,totalValue:round(list.reduce((a,o)=>a+(o.gross||o.net),0)),wonValue:won,status:current?.status||'kein Angebot'};}
export function integrateOfferIntoProjects(projects:Project[],offer:Offer):Project[]{return projects.map(p=>p.id!==offer.projectId?p:{...p,offers:[...p.offers.filter(o=>o.id!==offer.id),offer],financials:{...p.financials,expectedRevenueNet:offer.net,expectedRevenueGross:offer.gross||offer.net},value:offer.gross||offer.net,updatedAt:new Date().toISOString()});}
