import type {Appointment, Delivery, Invoice, Offer, Project, PurchaseOrder, SiteReport, Task, User} from '../types';

export type OperationTaskCategory='Angebot'|'Einkauf'|'Montage'|'Büro'|'Buchhaltung'|'Nacharbeit'|'Kunde'|'Material'|'Sonstiges';
export type OperationTaskStatus='Offen'|'In Bearbeitung'|'Wartet'|'Erledigt';
export interface OperationTaskComment{ id:string; createdAt:string; author:string; text:string; }
export interface OperationTaskAttachment{ id:string; name:string; url?:string; }
export interface OperationTask extends Task{ description:string; projectId?:string; project:string; customer:string; responsible:string; status:OperationTaskStatus; category:OperationTaskCategory; attachments:OperationTaskAttachment[]; comments:OperationTaskComment[]; }
export type CalendarEventType='Kundentermin'|'Montage'|'Lieferung'|'Aufmaß'|'Abnahme'|'Urlaub'|'Interner Termin';
export interface OperationsCalendarEvent{ id:string; title:string; date:string; type:CalendarEventType; href:string; projectId?:string; }
export interface InstallationPlan{ id:string; projectId:string; customer:string; address:string; teamIds:string[]; vehicleId:string; materialStatus:'Vollständig'|'Fehlt'|'Teilweise'; plannedDurationHours:number; notes:string; draggable:boolean; }
export interface TeamMember extends User{ phone:string; staffRole:string; skills:string[]; vacation:string[]; sick:boolean; availability:'Verfügbar'|'Eingeschränkt'|'Nicht verfügbar'; }
export interface Vehicle{ id:string; licensePlate:string; type:string; inspectionDue:string; serviceDue:string; tools:string[]; trailer:boolean; available:boolean; }
export interface MaterialCheckItem{ id:string; name:string; required:number; available:number; unit:string; }
export interface MaterialCheck{ projectId:string; complete:boolean; missingItems:MaterialCheckItem[]; }
export interface InstallationChecklistItem{ id:string; label:string; done:boolean; phase:'Vor Montage'|'Während Montage'|'Nach Montage'; }
export interface InstallationChecklist{ projectId:string; items:InstallationChecklistItem[]; }
export interface OperationsNotification{ id:string; type:'Material fehlt'|'Monteur krank'|'Lieferung verspätet'|'Neue Baustellenmeldung'|'Kunde wartet'|'Rechnung offen'; message:string; priority:'Normal'|'Wichtig'|'Dringend'; href:string; createdAt:string; read:boolean; }
export interface OperationsCenterState{ teamMembers:TeamMember[]; vehicles:Vehicle[]; installationPlans:InstallationPlan[]; materialChecks:MaterialCheck[]; installationChecklists:InstallationChecklist[]; operationsNotifications:OperationsNotification[]; }

const today='2026-07-22';
export const operationsDemoData:OperationsCenterState={
 teamMembers:[{id:'U-MONTAGE-1',name:'Max Montage',email:'max@example.invalid',role:'MITARBEITER',active:true,demoLogin:'max',assignedProjectIds:['P-003'],createdAt:today,updatedAt:today,phone:'+49 721 0001',staffRole:'Monteur',skills:['Terrassendach','Markise','Elektrik Basis'],vacation:[],sick:false,availability:'Verfügbar'},{id:'U-MONTAGE-2',name:'Ali Aufbau',email:'ali@example.invalid',role:'MITARBEITER',active:true,demoLogin:'ali',assignedProjectIds:['P-002'],createdAt:today,updatedAt:today,phone:'+49 721 0002',staffRole:'Vorarbeiter',skills:['Lamellendach','Abnahme'],vacation:['2026-08-03'],sick:false,availability:'Verfügbar'}],
 vehicles:[{id:'F-1',licensePlate:'KA KS 101',type:'Transporter lang',inspectionDue:'2026-11-30',serviceDue:'2026-09-15',tools:['Leitern','Akkuschrauber','Glasheber'],trailer:true,available:true},{id:'F-2',licensePlate:'KA KS 202',type:'Pritsche',inspectionDue:'2027-02-28',serviceDue:'2026-10-10',tools:['Montageböcke','Bohrhammer'],trailer:false,available:true}],
 installationPlans:[{id:'M-1',projectId:'P-003',customer:'Musterkunde',address:'Montageort Karlsruhe',teamIds:['U-MONTAGE-1','U-MONTAGE-2'],vehicleId:'F-1',materialStatus:'Fehlt',plannedDurationHours:8,notes:'Drag-&-Drop vorbereitet: Planungskarte kann später verschoben werden.',draggable:true}],
 materialChecks:[{projectId:'P-003',complete:false,missingItems:[{id:'MAT-1',name:'Seitenträger links',required:1,available:0,unit:'Stk.'},{id:'MAT-2',name:'Dichtungssatz',required:2,available:1,unit:'Set'}]}],
 installationChecklists:[{projectId:'P-003',items:[{id:'CL-1',phase:'Vor Montage',label:'Adresse und Ansprechpartner geprüft',done:true},{id:'CL-2',phase:'Vor Montage',label:'Materialcheck abgeschlossen',done:false},{id:'CL-3',phase:'Während Montage',label:'Befestigung dokumentiert',done:false},{id:'CL-4',phase:'Nach Montage',label:'Abnahmebilder hochgeladen',done:false}]}],
 operationsNotifications:[{id:'ON-1',type:'Material fehlt',message:'Projekt P-003: Seitenträger links fehlt.',priority:'Dringend',href:'/montageplanung',createdAt:today,read:false},{id:'ON-2',type:'Rechnung offen',message:'RE12763 ist offen und fällig am 30.07.2026.',priority:'Wichtig',href:'/rechnungen',createdAt:today,read:false}]
};
export function normalizeOperationTask(task:Task):OperationTask{const legacy=task as Partial<OperationTask>;return {id:task.id,title:task.title,due:task.due,priority:task.priority,done:task.done,projectId:task.projectId,assignedTo:task.assignedTo,description:legacy.description||'',project:legacy.project||'',customer:legacy.customer||'',responsible:legacy.responsible||task.assignedTo||'',status:legacy.status||(task.done?'Erledigt':'Offen'),category:legacy.category||'Sonstiges',attachments:legacy.attachments||[],comments:legacy.comments||[]};}
export function materialCheckForProject(projectId:string, checks:MaterialCheck[]):MaterialCheck{return checks.find(check=>check.projectId===projectId)||{projectId,complete:true,missingItems:[]};}
export function buildCalendarEvents(appointments:Appointment[], deliveries:Delivery[], projects:Project[]):OperationsCalendarEvent[]{const appointmentEvents=appointments.map(event=>({id:event.id,title:event.title,date:event.date,type:(event.type==='Interner Termin'?'Interner Termin':event.type) as CalendarEventType,href:event.projectId?`/projekte/${event.projectId}`:'/kalender',projectId:event.projectId}));const deliveryEvents=deliveries.map(delivery=>({id:delivery.id,title:`Lieferung ${delivery.deliveryNoteNumber}`,date:delivery.deliveryDate,type:'Lieferung' as const,href:'/lieferungen',projectId:delivery.projectId}));const installationEvents=projects.filter(project=>project.montage).map(project=>({id:`M-${project.id}`,title:`Montage ${project.customer}`,date:project.montage,type:'Montage' as const,href:`/projekte/${project.id}`,projectId:project.id}));return [...appointmentEvents,...deliveryEvents,...installationEvents].sort((a,b)=>a.date.localeCompare(b.date));}
export function todayWorkload(input:{date:string;projects:Project[];appointments:Appointment[];tasks:OperationTask[];offers:Offer[];purchaseOrders:PurchaseOrder[];deliveries:Delivery[];invoices:Invoice[];siteReports:SiteReport[]}){return {installations:input.projects.filter(project=>project.montage===input.date||project.plannedInstallationDate===input.date),customerAppointments:input.appointments.filter(appointment=>appointment.date===input.date&&appointment.type==='Kundentermin'),callbacks:input.tasks.filter(task=>task.category==='Kunde'&&task.status!=='Erledigt'),openOffers:input.offers.filter(offer=>!['Gewonnen','Verloren','Storniert'].includes(offer.status)),openPurchaseOrders:input.purchaseOrders.filter(order=>!['Geliefert','Storniert'].includes(order.status)),openSiteReports:input.siteReports.filter(report=>!['Erledigt','Abgelehnt'].includes(report.status)),materialDeliveries:input.deliveries.filter(delivery=>delivery.deliveryDate===input.date||delivery.status!=='Vollständig geliefert'),openInvoices:input.invoices.filter(invoice=>invoice.status!=='Bezahlt')};}
