import type {Employee,EmployeeAssignment,GeneralMessage,InventoryItem,MaterialRequirement,Offer,Project,PurchaseListItem,PurchaseOrder,SiteMessage,SiteMessageCategory,Tool,Vehicle,VehicleReminder,WorkTimeEntry} from '../types';
import {createPurchaseOrderNumber} from './purchasing';

const round=(n:number)=>Math.round(n*100)/100;
const minutes=(time:string):number=>{const [h='0',m='0']=time.split(':');return Number(h)*60+Number(m);};
const day=(date:string)=>new Date(`${date}T00:00:00.000Z`).getTime();
const dateOnly=(date:Date)=>date.toISOString().slice(0,10);
export const SITE_MESSAGE_CATEGORIES:SiteMessageCategory[]=['Schrauben fehlen','Dübel fehlen','Silikon fehlt','Dichtband fehlt','Kleinteile fehlen','Material fehlt','Werkzeug fehlt','Werkzeug defekt','Fahrzeugproblem','TÜV Hinweis','Service Hinweis','Kundenwunsch','Mangel','Nacharbeit','Sicherheitsproblem','Sonstiges'];
export const isOperationsAdmin=(name:string):boolean=>['Gökhan Karayel','Seda Karayel'].includes(name);
export function calculateWorkEntry(entry:WorkTimeEntry):WorkTimeEntry{const gross=Math.max(0,minutes(entry.endTime)-minutes(entry.startTime));return {...entry,breakMinutes:Math.max(0,entry.breakMinutes),travelMinutes:Math.max(0,entry.travelMinutes),netWorkMinutes:Math.max(0,gross-Math.max(0,entry.breakMinutes))};}
export function startWorkTime(entry:Omit<WorkTimeEntry,'startTime'|'endTime'|'breakMinutes'|'netWorkMinutes'|'status'|'createdAt'|'updatedAt'>,startTime:string,date=new Date()):WorkTimeEntry{const now=date.toISOString();return {...entry,startTime,endTime:startTime,breakMinutes:0,netWorkMinutes:0,status:'Entwurf',createdAt:now,updatedAt:now};}
export function addBreak(entry:WorkTimeEntry,breakMinutes:number,date=new Date()):WorkTimeEntry{return calculateWorkEntry({...entry,breakMinutes:entry.breakMinutes+Math.max(0,breakMinutes),updatedAt:date.toISOString()});}
export function endWorkTime(entry:WorkTimeEntry,endTime:string,date=new Date()):WorkTimeEntry{return calculateWorkEntry({...entry,endTime,status:'Eingereicht',updatedAt:date.toISOString()});}
export function workHours(entries:WorkTimeEntry[]):number{return round(entries.map(calculateWorkEntry).reduce((sum,e)=>sum+e.netWorkMinutes,0)/60);}
export function workHoursByProject(entries:WorkTimeEntry[],projectId:string):number{return workHours(entries.filter(e=>e.projectId===projectId));}
export function workHoursByWeek(entries:WorkTimeEntry[],employeeId:string,weekStart:string):number{const start=day(weekStart);const end=start+6*24*60*60*1000;return workHours(entries.filter(e=>e.employeeId===employeeId&&day(e.date)>=start&&day(e.date)<=end));}
export function canEmployeeEditTime(employeeId:string,entry:WorkTimeEntry):boolean{return entry.employeeId===employeeId&&entry.status!=='Freigegeben';}
export function assignedProjectsForEmployee(projects:Project[],assignments:EmployeeAssignment[],employeeId:string,date?:string):Project[]{const ids=new Set(assignments.filter(a=>a.employeeId===employeeId&&(!date||a.date===date)).map(a=>a.projectId));return projects.filter(p=>ids.has(p.id)||(!date&&p.assignedEmployeeIds?.includes(employeeId)));}
export function employeeProjectSections(projects:Project[],assignments:EmployeeAssignment[],employeeId:string,today=dateOnly(new Date())):{today:Project[];upcoming:Project[];past:Project[]}{const assigned=assignments.filter(a=>a.employeeId===employeeId);const section=(match:(a:EmployeeAssignment)=>boolean)=>projects.filter(p=>assigned.some(a=>a.projectId===p.id&&match(a))).sort((a,b)=>(a.plannedInstallationDate||'').localeCompare(b.plannedInstallationDate||''));return {today:section(a=>a.date===today),upcoming:section(a=>a.date>today),past:section(a=>a.date<today)};}
export function employeeProjectHistory(projectId:string,employeeId:string,workTimes:WorkTimeEntry[],messages:SiteMessage[]):{hours:number;messages:SiteMessage[];images:string[]}{const ownMessages=messages.filter(m=>m.projectId===projectId&&m.createdBy===employeeId);return {hours:workHours(workTimes.filter(e=>e.projectId===projectId&&e.employeeId===employeeId)),messages:ownMessages,images:ownMessages.flatMap(m=>m.images)};}
export function validateMinimumEmployees(employees:Employee[]):boolean{return employees.filter(e=>e.active).length>=6;}
export function inventoryNeedsPurchase(item:InventoryItem):boolean{return item.active&&item.currentStock<item.minimumStock;}
export function suggestInventoryPurchase(item:InventoryItem,createdBy:string,date=new Date()):PurchaseListItem|null{if(!inventoryNeedsPurchase(item))return null;const now=date.toISOString();return {id:`EKL-${item.id}`,source:'Lager-Mindestbestand',sourceReference:item.id,category:item.category,article:item.articleName,description:`Mindestbestand unterschritten (${item.currentStock} ${item.unit} < ${item.minimumStock} ${item.unit})`,quantity:Math.max(item.targetStock-item.currentStock,0),unit:item.unit,priority:'Wichtig',possibleSupplier:item.defaultSupplier,suggestedOrderRoute:'bestehendes Einkaufsmodul',estimatedPrice:item.lastPurchasePrice,status:'Offen',createdBy,note:'Vorschlag, keine automatische Bestellung.',images:[],createdAt:now,updatedAt:now};}
export function groupPurchaseListItems(items:PurchaseListItem[]):PurchaseListItem[]{const map=new Map<string,PurchaseListItem>();for(const item of items){const key=[item.article.trim().toLowerCase(),item.unit.trim().toLowerCase(),item.possibleSupplier||''].join('|');const source={projectId:item.projectId,constructionSite:item.constructionSite,quantity:item.quantity,unit:item.unit,sourceReference:item.sourceReference};const existing=map.get(key);if(!existing){map.set(key,{...item,groupedSources:[source]});continue;}const quantity=round(existing.quantity+item.quantity);map.set(key,{...existing,quantity,priority:priorityRank(item.priority)>priorityRank(existing.priority)?item.priority:existing.priority,sourceReference:[existing.sourceReference,item.sourceReference].filter(Boolean).join(','),note:[existing.note,item.note].filter(Boolean).join(' | '),groupedSources:[...(existing.groupedSources||[]),source]});}return Array.from(map.values()).sort((a,b)=>priorityRank(b.priority)-priorityRank(a.priority)||a.article.localeCompare(b.article));}
function priorityRank(p:string):number{return {'Baustopp':4,'Dringend':3,'Wichtig':2,'Normal':1}[p]||0;}
export function createPurchaseOrderDraftFromList(items:PurchaseListItem[],supplierId:string,supplierName:string,existing:PurchaseOrder[],date=new Date()):PurchaseOrder{const now=date.toISOString();const orderNumber=createPurchaseOrderNumber(existing,date);return {id:orderNumber,orderNumber,supplierId,supplierName,projectId:items[0]?.projectId,projectNumber:undefined,orderDate:now.slice(0,10),status:'Entwurf',items:items.map((item,index)=>({id:`${orderNumber}-POS-${index+1}`,name:item.article,description:item.description,quantity:item.quantity,unit:item.unit,unitPriceNet:item.estimatedPrice||0,discount:0,vatRate:19,netTotal:0,vatTotal:0,grossTotal:0})),netTotal:0,vatTotal:0,grossTotal:0,deliveryAddress:'KASTONIA Lager oder Baustelle laut Einkaufsliste',note:`Erstellt aus zentraler Einkaufsliste: ${items.map(i=>i.id).join(', ')}`,paymentStatus:'Offen',documentReferences:[],createdAt:now,updatedAt:now};}
export function syncPurchaseListStatus(item:PurchaseListItem,order?:PurchaseOrder):PurchaseListItem{if(!order)return item;const status=order.status==='Geliefert'?'Geliefert':order.status==='Teilweise geliefert'?'Teilweise geliefert':order.status==='Bestellt'?'Bestellt':item.status;return {...item,purchaseOrderId:order.id,status,updatedAt:order.updatedAt};}
export function materialRequirementsFromAcceptedOffer(offer:Offer,projectId:string):MaterialRequirement[]{if(offer.status!=='Gewonnen')return [];return offer.items.map(i=>({id:`MR-${offer.id}-${i.id}`,projectId,offerItemId:i.id,article:i.name,description:i.description,quantity:i.quantity,unit:i.unit,supplier:undefined,available:0,toOrder:i.quantity,ordered:0,delivered:0,onSite:0,note:'Entwurf aus angenommenem Angebot; manuell prüfen.'}));}
export function purchaseListFromSources(offers:Offer[],requirements:MaterialRequirement[],messages:SiteMessage[],inventory:InventoryItem[],tools:Tool[],vehicles:Vehicle[],createdBy:string,date=new Date()):PurchaseListItem[]{const now=date.toISOString();const fromOffer=offers.flatMap(o=>materialRequirementsFromAcceptedOffer(o,o.projectId||'').map(m=>({id:`EKL-${m.id}`,source:'Angebotsposition' as const,sourceReference:m.offerItemId,projectId:m.projectId,category:'Projektmaterial' as const,article:m.article,description:m.description,quantity:m.toOrder,unit:m.unit,priority:'Normal' as const,suggestedOrderRoute:'bestehendes Einkaufsmodul' as const,status:'Offen' as const,createdBy,note:m.note,images:[],createdAt:now,updatedAt:now})));const fromRequirements=requirements.filter(r=>r.toOrder>0).map(r=>({id:`EKL-${r.id}`,source:'Projektmaterialliste' as const,projectId:r.projectId,category:'Projektmaterial' as const,article:r.article,description:r.description,quantity:r.toOrder,unit:r.unit,priority:'Wichtig' as const,suggestedOrderRoute:'bestehendes Einkaufsmodul' as const,status:'Offen' as const,createdBy,note:r.note,images:[],createdAt:now,updatedAt:now}));const fromMessages=messages.filter(m=>m.purchaseRequired&&m.quantity).map(m=>({id:`EKL-${m.id}`,source:'Baustellenmeldung' as const,sourceReference:m.id,projectId:m.projectId,constructionSite:m.constructionSite,category:m.category.includes('Werkzeug')?'Werkzeug' as const:m.category.includes('Fahrzeug')?'Fahrzeug' as const:'Verbrauchsmaterial' as const,article:m.title,description:m.description,quantity:m.quantity||1,unit:m.unit||'Stk.',priority:m.priority,suggestedOrderRoute:'bestehendes Einkaufsmodul' as const,status:'Offen' as const,createdBy:m.createdBy,note:m.category,images:m.images,createdAt:now,updatedAt:now}));const fromInventory=inventory.map(i=>suggestInventoryPurchase(i,createdBy,date)).filter((i):i is PurchaseListItem=>Boolean(i));const fromTools=tools.filter(t=>['Defekt','defekt','Verloren','verloren'].includes(t.status)).map(t=>toolPurchaseListItem(t,createdBy,date));const fromVehicles=vehicles.filter(v=>vehicleReminders(v,date,true).length>0).map(v=>({id:`EKL-${v.id}`,source:'Fahrzeug' as const,sourceReference:v.id,category:'Fahrzeug' as const,article:`Fahrzeugprüfung ${v.licensePlate}`,description:vehicleReminders(v,date,true).join(', '),quantity:1,unit:'Service',priority:'Wichtig' as const,suggestedOrderRoute:'manuell prüfen' as const,status:'Offen' as const,createdBy,note:v.notes,images:v.images,createdAt:now,updatedAt:now}));return groupPurchaseListItems([...fromOffer,...fromRequirements,...fromMessages,...fromInventory,...fromTools,...fromVehicles]);}
export function toolPurchaseListItem(tool:Tool,createdBy:string,date=new Date()):PurchaseListItem{const now=date.toISOString();return {id:`EKL-${tool.id}`,source:'Werkzeug',sourceReference:tool.id,category:tool.status==='Verloren'||tool.status==='verloren'?'Ersatzwerkzeug':'Werkzeug',article:tool.name,description:`Werkzeugstatus: ${tool.status}. ${tool.manufacturer} ${tool.model}`.trim(),quantity:1,unit:'Stk.',priority:tool.status==='Defekt'||tool.status==='defekt'?'Wichtig':'Dringend',suggestedOrderRoute:'bestehendes Einkaufsmodul',status:'Offen',createdBy,note:tool.notes,images:tool.images,createdAt:now,updatedAt:now};}
export function vehicleReminders(vehicle:Vehicle,today=new Date(),openDamage=false):VehicleReminder[]{const reminders:VehicleReminder[]=[];const diff=Math.ceil((day(vehicle.tuvValidUntil)-day(dateOnly(today)))/(1000*60*60*24));if(diff<0)reminders.push('TÜV überfällig');else if(diff<=30)reminders.push('TÜV in 30 Tagen fällig');else if(diff<=90)reminders.push('TÜV in 90 Tagen fällig');if(vehicle.nextServiceMileage&&vehicle.mileage>=vehicle.nextServiceMileage)reminders.push('Service überfällig');else if(vehicle.nextServiceMileage&&vehicle.nextServiceMileage-vehicle.mileage<=1000)reminders.push('Service bald fällig');if(openDamage)reminders.push('Fahrzeugschaden offen');if(vehicle.status==='Gesperrt')reminders.push('Fahrzeug gesperrt');return reminders;}
export function dashboardOperationsMetrics(messages:SiteMessage[],vehicles:Vehicle[],assignments:EmployeeAssignment[],projects:Project[],today=dateOnly(new Date())){const todaysProjectIds=new Set(assignments.filter(a=>a.date===today).map(a=>a.projectId));const workers=new Set(assignments.filter(a=>a.date===today).map(a=>a.employeeId));return {todaysSites:todaysProjectIds.size,monteursOnRoad:workers.size,openMaterialMessages:messages.filter(m=>!['Erledigt','Abgelehnt'].includes(m.status)&&m.category.includes('Material')).length,openToolMessages:messages.filter(m=>!['Erledigt','Abgelehnt'].includes(m.status)&&m.category.includes('Werkzeug')).length,openVehicleMessages:messages.filter(m=>!['Erledigt','Abgelehnt'].includes(m.status)&&m.category.includes('Fahrzeug')).length,tuvDueSoon:vehicles.filter(v=>vehicleReminders(v,new Date(`${today}T00:00:00.000Z`)).some(r=>r.includes('TÜV'))).length,missingMaterial:messages.filter(m=>!['Erledigt','Abgelehnt'].includes(m.status)&&m.title.toLowerCase().includes('fehlt')).length,openRework:projects.filter(p=>p.status==='Nacharbeit').length};}
export function notificationsForOperations(messages:SiteMessage[],vehicles:Vehicle[],general:GeneralMessage[]):string[]{return [...messages.filter(m=>m.priority==='Baustopp'||m.priority==='Dringend'||m.category.includes('Werkzeug')||m.category.includes('Fahrzeug')).map(m=>`${m.priority}: ${m.title}`),...vehicles.flatMap(v=>vehicleReminders(v).map(r=>`${v.licensePlate}: ${r}`)),...general.filter(g=>g.priority==='Dringend').map(g=>`Mitteilung: ${g.subject}`)];}
