import type {Employee,EmployeeAssignment,GeneralMessage,InventoryItem,MaterialRequirement,Offer,Project,PurchaseListItem,PurchaseOrder,SiteMessage,Vehicle,VehicleReminder,WorkTimeEntry} from '../types';
import {createPurchaseOrderNumber} from './purchasing';

const round=(n:number)=>Math.round(n*100)/100;
const minutes=(time:string):number=>{const [h='0',m='0']=time.split(':');return Number(h)*60+Number(m);};
const day=(date:string)=>new Date(`${date}T00:00:00.000Z`).getTime();
export const isOperationsAdmin=(name:string):boolean=>['Gökhan Karayel','Seda Karayel'].includes(name);
export function calculateWorkEntry(entry:WorkTimeEntry):WorkTimeEntry{const gross=Math.max(0,minutes(entry.endTime)-minutes(entry.startTime));return {...entry,breakMinutes:Math.max(0,entry.breakMinutes),travelMinutes:Math.max(0,entry.travelMinutes),netWorkMinutes:Math.max(0,gross-Math.max(0,entry.breakMinutes))};}
export function workHours(entries:WorkTimeEntry[]):number{return round(entries.map(calculateWorkEntry).reduce((sum,e)=>sum+e.netWorkMinutes,0)/60);}
export function workHoursByProject(entries:WorkTimeEntry[],projectId:string):number{return workHours(entries.filter(e=>e.projectId===projectId));}
export function canEmployeeEditTime(employeeId:string,entry:WorkTimeEntry):boolean{return entry.employeeId===employeeId&&entry.status!=='Freigegeben';}
export function assignedProjectsForEmployee(projects:Project[],assignments:EmployeeAssignment[],employeeId:string,date?:string):Project[]{const ids=new Set(assignments.filter(a=>a.employeeId===employeeId&&(!date||a.date===date)).map(a=>a.projectId));return projects.filter(p=>ids.has(p.id)||p.assignedEmployeeIds?.includes(employeeId));}
export function validateMinimumEmployees(employees:Employee[]):boolean{return employees.filter(e=>e.active).length>=6;}
export function inventoryNeedsPurchase(item:InventoryItem):boolean{return item.active&&item.currentStock<item.minimumStock;}
export function suggestInventoryPurchase(item:InventoryItem,createdBy:string,date=new Date()):PurchaseListItem|null{if(!inventoryNeedsPurchase(item))return null;const now=date.toISOString();return {id:`EKL-${item.id}`,source:'Lager-Mindestbestand',sourceReference:item.id,category:item.category,article:item.articleName,description:`Mindestbestand unterschritten (${item.currentStock} ${item.unit} < ${item.minimumStock} ${item.unit})`,quantity:Math.max(item.targetStock-item.currentStock,0),unit:item.unit,priority:'Wichtig',possibleSupplier:item.defaultSupplier,suggestedOrderRoute:'bestehendes Einkaufsmodul',estimatedPrice:item.lastPurchasePrice,status:'Offen',createdBy,note:'Vorschlag, keine automatische Bestellung.',images:[],createdAt:now,updatedAt:now};}
export function groupPurchaseListItems(items:PurchaseListItem[]):PurchaseListItem[]{const map=new Map<string,PurchaseListItem>();for(const item of items){const key=[item.article.toLowerCase(),item.unit,item.possibleSupplier||'',item.projectId||''].join('|');const existing=map.get(key);if(!existing){map.set(key,{...item});continue;}map.set(key,{...existing,quantity:round(existing.quantity+item.quantity),sourceReference:[existing.sourceReference,item.sourceReference].filter(Boolean).join(','),note:[existing.note,item.note].filter(Boolean).join(' | ')});}return Array.from(map.values()).sort((a,b)=>priorityRank(b.priority)-priorityRank(a.priority));}
function priorityRank(p:string):number{return {'Baustopp':4,'Dringend':3,'Wichtig':2,'Normal':1}[p]||0;}
export function createPurchaseOrderDraftFromList(items:PurchaseListItem[],supplierId:string,supplierName:string,existing:PurchaseOrder[],date=new Date()):PurchaseOrder{const now=date.toISOString();const orderNumber=createPurchaseOrderNumber(existing,date);return {id:orderNumber,orderNumber,supplierId,supplierName,projectId:items[0]?.projectId,projectNumber:undefined,orderDate:now.slice(0,10),status:'Entwurf',items:items.map((item,index)=>({id:`${orderNumber}-POS-${index+1}`,name:item.article,description:item.description,quantity:item.quantity,unit:item.unit,unitPriceNet:item.estimatedPrice||0,discount:0,vatRate:19,netTotal:0,vatTotal:0,grossTotal:0})),netTotal:0,vatTotal:0,grossTotal:0,deliveryAddress:'KASTONIA Lager oder Baustelle laut Einkaufsliste',note:`Erstellt aus zentraler Einkaufsliste: ${items.map(i=>i.id).join(', ')}`,paymentStatus:'Offen',documentReferences:[],createdAt:now,updatedAt:now};}
export function syncPurchaseListStatus(item:PurchaseListItem,order?:PurchaseOrder):PurchaseListItem{if(!order)return item;const status=order.status==='Geliefert'?'Geliefert':order.status==='Teilweise geliefert'?'Teilweise geliefert':order.status==='Bestellt'?'Bestellt':item.status;return {...item,purchaseOrderId:order.id,status,updatedAt:order.updatedAt};}
export function materialRequirementsFromAcceptedOffer(offer:Offer,projectId:string):MaterialRequirement[]{if(offer.status!=='Gewonnen')return [];return offer.items.map(i=>({id:`MR-${offer.id}-${i.id}`,projectId,offerItemId:i.id,article:i.name,description:i.description,quantity:i.quantity,unit:i.unit,supplier:undefined,available:0,toOrder:i.quantity,ordered:0,delivered:0,onSite:0,note:'Entwurf aus angenommenem Angebot; manuell prüfen.'}));}
export function vehicleReminders(vehicle:Vehicle,today=new Date(),openDamage=false):VehicleReminder[]{const reminders:VehicleReminder[]=[];const diff=Math.ceil((day(vehicle.tuvValidUntil)-day(today.toISOString().slice(0,10)))/(1000*60*60*24));if(diff<0)reminders.push('TÜV überfällig');else if(diff<=30)reminders.push('TÜV in 30 Tagen fällig');else if(diff<=90)reminders.push('TÜV in 90 Tagen fällig');if(vehicle.nextServiceMileage&&vehicle.mileage>=vehicle.nextServiceMileage)reminders.push('Service überfällig');else if(vehicle.nextServiceMileage&&vehicle.nextServiceMileage-vehicle.mileage<=1000)reminders.push('Service bald fällig');if(openDamage)reminders.push('Fahrzeugschaden offen');if(vehicle.status==='Gesperrt')reminders.push('Fahrzeug gesperrt');return reminders;}
export function notificationsForOperations(messages:SiteMessage[],vehicles:Vehicle[],general:GeneralMessage[]):string[]{return [...messages.filter(m=>m.priority==='Baustopp'||m.priority==='Dringend'||m.category.includes('Werkzeug')||m.category.includes('Fahrzeug')).map(m=>`${m.priority}: ${m.title}`),...vehicles.flatMap(v=>vehicleReminders(v).map(r=>`${v.licensePlate}: ${r}`)),...general.filter(g=>g.priority==='Dringend').map(g=>`Mitteilung: ${g.subject}`)];}
