import type {Delivery,DeliveryItem,DeliveryStatus,Project,PurchaseOrder,PurchaseOrderItem,PurchaseOrderStatus,StateLikeSupplier} from '../types';

const round=(n:number)=>Math.round((Number.isFinite(n)?n:0)*100)/100;
export const PURCHASE_ORDER_STATUSES: PurchaseOrderStatus[]=['Entwurf','Angefragt','Bestellt','Teilweise geliefert','Geliefert','Storniert'];
export const PAYMENT_STATUSES: PurchaseOrder['paymentStatus'][]=['Offen','Teilweise bezahlt','Bezahlt'];
export const DELIVERY_STATUSES: DeliveryStatus[]=['Erwartet','Teilweise geliefert','Vollständig geliefert','Beschädigt','Reklamation offen'];

export function createPurchaseOrderNumber(existing:Pick<PurchaseOrder,'orderNumber'|'id'>[],date=new Date()):string{const prefix=`BE${date.getFullYear()}`;const nums=existing.map(o=>o.orderNumber||o.id).filter(n=>n.startsWith(prefix)).map(n=>Number(n.slice(prefix.length,prefix.length+4))).filter(Number.isFinite);return `${prefix}${String(Math.max(0,...nums)+1).padStart(4,'0')}`;}
export function calculatePurchaseItem(item:PurchaseOrderItem):PurchaseOrderItem{const quantity=Math.max(0,item.quantity||0);const price=Math.max(0,item.unitPriceNet||0);const discount=Math.min(100,Math.max(0,item.discount||0));const net=round(quantity*price*(1-discount/100));const vat=round(net*((item.vatRate||0)/100));return {...item,quantity,unitPriceNet:price,discount,netTotal:net,vatTotal:vat,grossTotal:round(net+vat)};}
export function calculatePurchaseOrder(order:PurchaseOrder,date=new Date()):PurchaseOrder{const items=order.items.map(calculatePurchaseItem);const net=round(items.reduce((a,i)=>a+i.netTotal,0));const vat=round(items.reduce((a,i)=>a+i.vatTotal,0));return {...order,items,netTotal:net,vatTotal:vat,grossTotal:round(net+vat),updatedAt:date.toISOString()};}
export function duplicatePurchaseOrder(order:PurchaseOrder,existing:PurchaseOrder[],date=new Date()):PurchaseOrder{const orderNumber=createPurchaseOrderNumber(existing,date);const now=date.toISOString();return calculatePurchaseOrder({...order,id:orderNumber,orderNumber,status:'Entwurf',paymentStatus:'Offen',orderDate:now.slice(0,10),actualDeliveryDate:undefined,documentReferences:[...order.documentReferences],items:order.items.map((i,index)=>({...i,id:`${orderNumber}-POS-${index+1}`})),createdAt:now,updatedAt:now},date);}
export function receivedQuantityForItem(orderItemId:string,deliveries:Delivery[]):number{return deliveries.flatMap(d=>d.items).filter(i=>i.orderItemId===orderItemId).reduce((a,i)=>a+i.deliveredQuantity,0);}
export function remainingQuantityForItem(orderItem:PurchaseOrderItem,deliveries:Delivery[]):number{return Math.max(0,round(orderItem.quantity-receivedQuantityForItem(orderItem.id,deliveries)));}
export function calculateDeliveryStatus(order:PurchaseOrder,items:DeliveryItem[]):DeliveryStatus{const damaged=items.some(i=>i.damagedQuantity>0);const missing=items.some(i=>i.missingQuantity>0);const delivered=items.reduce((a,i)=>a+i.deliveredQuantity,0);const complete=order.items.length>0&&order.items.every(oi=>items.filter(i=>i.orderItemId===oi.id).reduce((a,i)=>a+i.deliveredQuantity,0)>=oi.quantity);if(damaged&&missing)return 'Reklamation offen';if(damaged)return 'Beschädigt';if(complete)return 'Vollständig geliefert';return delivered>0?'Teilweise geliefert':'Erwartet';}
export function updateOrderStatusFromDeliveries(order:PurchaseOrder,deliveries:Delivery[],date=new Date()):PurchaseOrder{if(order.status==='Storniert'||order.status==='Entwurf'||order.status==='Angefragt')return order;const related=deliveries.filter(d=>d.purchaseOrderId===order.id);if(related.length===0)return order;const total=order.items.reduce((a,i)=>a+i.quantity,0);const delivered=order.items.reduce((a,i)=>a+receivedQuantityForItem(i.id,related),0);const damaged=related.flatMap(d=>d.items).reduce((a,i)=>a+i.damagedQuantity,0);const status:PurchaseOrderStatus=damaged>0?'Teilweise geliefert':delivered>=total?'Geliefert':delivered>0?'Teilweise geliefert':order.status;return {...order,status,actualDeliveryDate:status==='Geliefert'?[...related].sort((a,b)=>b.deliveryDate.localeCompare(a.deliveryDate))[0]?.deliveryDate:order.actualDeliveryDate,updatedAt:date.toISOString()};}
export function createDelivery(order:PurchaseOrder,items:DeliveryItem[],date=new Date()):Delivery{const now=date.toISOString();return {id:`WE-${Date.now()}`,purchaseOrderId:order.id,projectId:order.projectId,deliveryNoteNumber:'',deliveryDate:now.slice(0,10),items,status:calculateDeliveryStatus(order,items),notes:'',documentReferences:[]};}
export function isDeliveryOverdue(order:PurchaseOrder,today=new Date()):boolean{return Boolean(order.expectedDeliveryDate&&!['Geliefert','Storniert'].includes(order.status)&&new Date(order.expectedDeliveryDate+'T23:59:59').getTime()<today.getTime());}
export function updateProjectProgressFromProcurement(projects:Project[],orders:PurchaseOrder[],date=new Date()):Project[]{return projects.map(project=>{const related=orders.filter(o=>o.projectId===project.id);if(!related.length)return project;const hasOpen=related.some(o=>['Bestellt','Teilweise geliefert'].includes(o.status));const allDelivered=related.every(o=>o.status==='Geliefert'||o.status==='Storniert');const expectedCostNet=round(related.reduce((a,o)=>a+o.netTotal,0));const expectedCostGross=round(related.reduce((a,o)=>a+o.grossTotal,0));const status=allDelivered&&project.status==='Material ausstehend'?'Montage geplant':hasOpen&&['Auftrag erhalten','Auftragsbestätigung','Bestellung Lieferant'].includes(project.status)?'Material ausstehend':project.status;const phase=status==='Material ausstehend'?'Einkauf':status==='Montage geplant'?'Montage':project.phase;return {...project,status,phase,financials:{...project.financials,expectedCostNet,expectedCostGross},updatedAt:date.toISOString()};});}
export function normalizeSupplier(raw:Partial<StateLikeSupplier> & {id:string},index=0):StateLikeSupplier{const now=new Date().toISOString();const companyName=raw.companyName||raw.name||'Unbenannter Lieferant';const contactPerson=raw.contactPerson||raw.contact||'';const address=raw.address||'';const contactPersons=raw.contactPersons?.length?raw.contactPersons:(contactPerson?[{id:`${raw.id||`L-${index+1}`}-K1`,name:contactPerson,email:raw.email,phone:raw.phone}]:[]);return {id:raw.id||`L-${index+1}`,companyName,contactPerson,contactPersons,address,addresses:raw.addresses?.length?raw.addresses:[{id:`${raw.id||`L-${index+1}`}-A1`,type:'Zentrale',street:address,postalCode:'',city:'',country:raw.country||'DE'}],country:raw.country||'DE',email:raw.email||'',phone:raw.phone||'',website:raw.website||'',supplierCustomerNumber:raw.supplierCustomerNumber||'',paymentTerms:raw.paymentTerms||'14 Tage netto',usualDeliveryTime:raw.usualDeliveryTime||'',categories:raw.categories?.length?raw.categories:[raw.category||'Allgemein'],contactInfo:raw.contactInfo||[raw.email,raw.phone,raw.website].filter(Boolean).join(' · '),history:raw.history||[],projectIds:raw.projectIds||[],notes:raw.notes||'',active:raw.active!==false,createdAt:raw.createdAt||now,updatedAt:raw.updatedAt||now};}
