import type {Delivery,DeliveryItem,DeliveryStatus,PurchaseOrder,PurchaseOrderItem,PurchaseOrderStatus,StateLikeSupplier} from '../types';

const round=(n:number)=>Math.round((Number.isFinite(n)?n:0)*100)/100;
export const PURCHASE_ORDER_STATUSES: PurchaseOrderStatus[]=['Entwurf','Angefragt','Bestellt','Teilweise geliefert','Geliefert','Storniert'];
export const PAYMENT_STATUSES: PurchaseOrder['paymentStatus'][]=['Offen','Teilweise bezahlt','Bezahlt'];
export const DELIVERY_STATUSES: DeliveryStatus[]=['Erwartet','Teilweise geliefert','Vollständig geliefert','Beschädigt','Reklamation offen'];

export function createPurchaseOrderNumber(existing:Pick<PurchaseOrder,'orderNumber'|'id'>[],date=new Date()):string{const prefix=`BE${date.getFullYear()}`;const nums=existing.map(o=>o.orderNumber||o.id).filter(n=>n.startsWith(prefix)).map(n=>Number(n.slice(prefix.length,prefix.length+4))).filter(Number.isFinite);return `${prefix}${String(Math.max(0,...nums)+1).padStart(4,'0')}`;}
export function calculatePurchaseItem(item:PurchaseOrderItem):PurchaseOrderItem{const quantity=Math.max(0,item.quantity||0);const price=Math.max(0,item.unitPriceNet||0);const discount=Math.max(0,item.discount||0);const net=round(quantity*price*(1-discount/100));const vat=round(net*((item.vatRate||0)/100));return {...item,quantity,unitPriceNet:price,discount,netTotal:net,vatTotal:vat,grossTotal:round(net+vat)};}
export function calculatePurchaseOrder(order:PurchaseOrder):PurchaseOrder{const items=order.items.map(calculatePurchaseItem);const net=round(items.reduce((a,i)=>a+i.netTotal,0));const vat=round(items.reduce((a,i)=>a+i.vatTotal,0));return {...order,items,netTotal:net,vatTotal:vat,grossTotal:round(net+vat),updatedAt:new Date().toISOString()};}
export function duplicatePurchaseOrder(order:PurchaseOrder,existing:PurchaseOrder[],date=new Date()):PurchaseOrder{const orderNumber=createPurchaseOrderNumber(existing,date);const now=date.toISOString();return calculatePurchaseOrder({...order,id:orderNumber,orderNumber,status:'Entwurf',paymentStatus:'Offen',orderDate:now.slice(0,10),actualDeliveryDate:undefined,documentReferences:[...order.documentReferences],items:order.items.map((i,index)=>({...i,id:`${orderNumber}-POS-${index+1}`})),createdAt:now,updatedAt:now});}
export function receivedQuantityForItem(orderItemId:string,deliveries:Delivery[]):number{return deliveries.flatMap(d=>d.items).filter(i=>i.orderItemId===orderItemId).reduce((a,i)=>a+i.deliveredQuantity,0);}
export function remainingQuantityForItem(orderItem:PurchaseOrderItem,deliveries:Delivery[]):number{return Math.max(0,round(orderItem.quantity-receivedQuantityForItem(orderItem.id,deliveries)));}
export function updateOrderStatusFromDeliveries(order:PurchaseOrder,deliveries:Delivery[]):PurchaseOrder{if(order.status==='Storniert'||order.status==='Entwurf'||order.status==='Angefragt')return order;const related=deliveries.filter(d=>d.purchaseOrderId===order.id);if(related.length===0)return order;const total=order.items.reduce((a,i)=>a+i.quantity,0);const delivered=order.items.reduce((a,i)=>a+receivedQuantityForItem(i.id,related),0);const damaged=related.flatMap(d=>d.items).reduce((a,i)=>a+i.damagedQuantity,0);const status:PurchaseOrderStatus=damaged>0?'Teilweise geliefert':delivered>=total?'Geliefert':delivered>0?'Teilweise geliefert':order.status;return {...order,status,actualDeliveryDate:status==='Geliefert'?[...related].sort((a,b)=>b.deliveryDate.localeCompare(a.deliveryDate))[0]?.deliveryDate:order.actualDeliveryDate,updatedAt:new Date().toISOString()};}
export function createDelivery(order:PurchaseOrder,items:DeliveryItem[],date=new Date()):Delivery{const now=date.toISOString();const hasDamage=items.some(i=>i.damagedQuantity>0);const complete=order.items.every(oi=>items.filter(i=>i.orderItemId===oi.id).reduce((a,i)=>a+i.deliveredQuantity,0)>=oi.quantity);return {id:`WE-${Date.now()}`,purchaseOrderId:order.id,projectId:order.projectId,deliveryNoteNumber:'',deliveryDate:now.slice(0,10),items,status:hasDamage?'Beschädigt':complete?'Vollständig geliefert':'Teilweise geliefert',notes:'',documentReferences:[]};}
export function isDeliveryOverdue(order:PurchaseOrder,today=new Date()):boolean{return Boolean(order.expectedDeliveryDate&&!['Geliefert','Storniert'].includes(order.status)&&new Date(order.expectedDeliveryDate+'T23:59:59').getTime()<today.getTime());}
export function normalizeSupplier(raw:Partial<StateLikeSupplier> & {id:string},index=0):StateLikeSupplier{const now=new Date().toISOString();return {id:raw.id||`L-${index+1}`,companyName:raw.companyName||raw.name||'Unbenannter Lieferant',contactPerson:raw.contactPerson||raw.contact||'',address:raw.address||'',country:raw.country||'DE',email:raw.email||'',phone:raw.phone||'',website:raw.website||'',supplierCustomerNumber:raw.supplierCustomerNumber||'',paymentTerms:raw.paymentTerms||'14 Tage netto',usualDeliveryTime:raw.usualDeliveryTime||'',categories:raw.categories||[raw.category||'Allgemein'],notes:raw.notes||'',active:raw.active!==false,createdAt:raw.createdAt||now,updatedAt:raw.updatedAt||now};}
