import type {Notification,Project,ProjectTimelineEntry,SiteReport,SiteReportImage,SiteReportStatus,User} from '../types';
import {assertPermission,assertProjectAccess,canManageSiteReport} from './permissions';

const now=()=>new Date().toISOString();
const id=(prefix:string)=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
export function createStorageReference(fileName:string,fileType:string,reference:string){return {provider:'local-reference' as const,reference,fileName,fileType};}
export function createSiteReport(input:Omit<SiteReport,'id'|'createdAt'|'updatedAt'|'status'|'images'|'comments'> & {images?:SiteReportImage[]}, project:Project, user:User, at=now()):{report:SiteReport;timeline:ProjectTimelineEntry[];notifications:Notification[]}{assertPermission(user,'siteReports:create');assertProjectAccess(user,project);const report:SiteReport={...input,id:id('BM'),status:'Neu',images:input.images||[],comments:[],createdAt:at,updatedAt:at};const timeline=[timelineEntry(project.id,user,'Baustellenmeldung erstellt',`${report.category}: ${report.title}`,report.id,at)];const notifications=createNotificationsForReport(report,project,user,at);return {report,timeline,notifications};}
export function addImageToReport(report:SiteReport,image:SiteReportImage,project:Project,user:User,at=now()):{report:SiteReport;timeline:ProjectTimelineEntry[]}{if(!canManageSiteReport(user,report))throw new Error('Zugriff verweigert: Meldungsbild');assertProjectAccess(user,project);return {report:{...report,images:[...report.images,image],updatedAt:at},timeline:[timelineEntry(project.id,user,'Bild hinzugefügt',`${image.category}: ${image.fileName}`,report.id,at)]};}
export function changeSiteReportStatus(report:SiteReport,status:SiteReportStatus,user:User,at=now(),internalResponse?:string):{report:SiteReport;timeline:ProjectTimelineEntry[];notifications:Notification[]}{if(user.role!=='ADMIN'&&!canManageSiteReport(user,report))throw new Error('Zugriff verweigert: Statusänderung');const closedAt=status==='Erledigt'||status==='Abgelehnt'?at:report.closedAt;const updated={...report,status,internalResponse:internalResponse??report.internalResponse,closedAt,updatedAt:at};return {report:updated,timeline:[timelineEntry(report.projectId,user,status==='Erledigt'?'Meldung abgeschlossen':'Status geändert',`Meldung ${report.id}: ${status}`,report.id,at)],notifications:[{id:id('N'),userId:report.createdBy,type:'STATUS_CHANGE',title:'Status deiner Meldung geändert',message:`${report.title}: ${status}`,createdAt:at,projectId:report.projectId,siteReportId:report.id,channel:'internal',priority:report.priority}]};}
export function preparePurchaseFromMaterialReport(report:SiteReport,user:User,purchaseOrderId?:string):SiteReport{assertPermission(user,'purchasing:manage');if(report.category!=='Material nachbestellen')throw new Error('Nur Materialmeldungen können mit Einkauf verknüpft werden.');return {...report,status:'Bestellt',materialDetails:report.materialDetails?{...report.materialDetails,linkedPurchaseOrderId:purchaseOrderId}:report.materialDetails,updatedAt:now()};}
export function markToolProvided(report:SiteReport,user:User,at=now()):SiteReport{assertPermission(user,'siteReports:write');if(report.category!=='Werkzeug benötigt')throw new Error('Nur Werkzeugmeldungen können bereitgestellt werden.');return {...report,status:'Erledigt',closedAt:at,toolDetails:report.toolDetails?{...report.toolDetails,providedAt:at}:report.toolDetails,updatedAt:at};}
export function timelineEntry(projectId:string,user:User,eventType:ProjectTimelineEntry['eventType'],description:string,siteReportId?:string,at=now()):ProjectTimelineEntry{return {id:id('TL'),eventType,createdAt:at,userId:user.id,userName:user.name,description,projectId,siteReportId};}
export function createNotificationsForReport(report:SiteReport,project:Project,user:User,at=now()):Notification[]{const important=report.priority==='Dringend'||report.priority==='Baustopp'||['Material nachbestellen','Werkzeug benötigt','Mangel','Abnahmebilder'].includes(report.category);if(!important)return [];return [{id:id('N'),userId:project.responsibleAdminId||'U-ADMIN-GK',type:'SITE_REPORT',title:report.priority==='Baustopp'?'Baustopp-Meldung':'Neue Baustellenmeldung',message:`${project.projectNumber}: ${report.title}`,createdAt:at,projectId:project.id,siteReportId:report.id,channel:'internal',priority:report.priority}];}
