import type {Employee,EmployeeAssignment,Project,Vehicle} from '../types';
import type {BridgeDay,CompanyHolidayPeriod,EmployeeAvailability,WorkdayConfiguration,WorkforceCapacity} from './workforce-availability';
import {calculateWorkforceCapacity,entriesForDate,rangesOverlap} from './workforce-availability';

export type CalendarStatusKey='present'|'timeOffOpen'|'timeOffApproved'|'timeOffRejected'|'absence'|'planned'|'companyHoliday'|'blocked'|'noResponse'|'workday'|'bridgeDay'|'specialWorkday';
export const STATUS_PRESENTATION:Record<CalendarStatusKey,{label:string;icon:string;tone:string;tooltip:string}>={
 present:{label:'Anwesend',icon:'check',tone:'green',tooltip:'Mitarbeiter hat Anwesenheit bestätigt.'},
 timeOffOpen:{label:'Freiwunsch offen',icon:'hourglass',tone:'amber',tooltip:'Freiwunsch wartet auf Entscheidung.'},
 timeOffApproved:{label:'Freiwunsch genehmigt',icon:'check-circle',tone:'blue',tooltip:'Freiwunsch wurde genehmigt.'},
 timeOffRejected:{label:'Freiwunsch abgelehnt',icon:'x-circle',tone:'red',tooltip:'Freiwunsch wurde abgelehnt.'},
 absence:{label:'Sonstige Abwesenheit',icon:'minus-circle',tone:'red',tooltip:'Abwesenheit ist gemeldet oder bestätigt.'},
 planned:{label:'Eingeplant',icon:'briefcase',tone:'violet',tooltip:'Mitarbeiter ist einem Einsatz zugewiesen.'},
 companyHoliday:{label:'Betriebsferien',icon:'building',tone:'slate',tooltip:'Zeitraum ist als Betriebsferien markiert.'},
 blocked:{label:'Gesperrt',icon:'lock',tone:'red',tooltip:'Arbeitstag ist gesperrt oder nicht planbar.'},
 noResponse:{label:'Noch keine Rückmeldung',icon:'circle-dashed',tone:'slate',tooltip:'Für diesen relevanten Arbeitstag liegt keine Rückmeldung vor.'},
 workday:{label:'Arbeitstag freigegeben',icon:'calendar-check',tone:'green',tooltip:'Dieser KASTONIA-Arbeitstag ist freigegeben.'},
 bridgeDay:{label:'Brückentag',icon:'route',tone:'amber',tooltip:'Dieser relevante Tag ist als Brückentag hinterlegt.'},
 specialWorkday:{label:'Sonderarbeitstag',icon:'sparkle',tone:'blue',tooltip:'Dieser Tag wurde zusätzlich als Arbeitstag freigegeben.'}
};
export const monthNames=['Januar','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember'];
export function formatDateLong(date:string){return new Intl.DateTimeFormat('de-DE',{weekday:'long',day:'numeric',month:'long'}).format(new Date(`${date}T00:00:00Z`));}
export function isSaturday(date:string){return new Date(`${date}T00:00:00Z`).getUTCDay()===6;}
export function isCompanyHoliday(date:string,holidays:CompanyHolidayPeriod[]){return holidays.find(h=>!h.archived&&rangesOverlap(h.startDate,h.endDate,date,date));}
export function workdayInfo(date:string,workdays:WorkdayConfiguration[],bridgeDays:BridgeDay[],holidays:CompanyHolidayPeriod[]){const workday=workdays.find(w=>w.date===date);const bridge=bridgeDays.find(b=>b.date===date);const holiday=isCompanyHoliday(date,holidays);const relevant=Boolean(holiday||bridge||workday||isSaturday(date));const allowed=Boolean((workday?.workAllowed||bridge?.workAllowed)&&!holiday);const status:CalendarStatusKey=holiday?'companyHoliday':workday?.status==='gesperrt'||bridge?.status==='gesperrt'?'blocked':workday?.status==='Sonderarbeitstag'?'specialWorkday':bridge?'bridgeDay':allowed?'workday':isSaturday(date)?'blocked':'noResponse';return {relevant,allowed,status,label:holiday?.title||workday?.label||bridge?.title||STATUS_PRESENTATION[status].label};}
export function relevantWorkdays(year:number,workdays:WorkdayConfiguration[],bridgeDays:BridgeDay[],holidays:CompanyHolidayPeriod[],showAll=false){const dates:string[]=[];for(let i=0;i<366;i++){const d=new Date(Date.UTC(year,0,1+i));if(d.getUTCFullYear()!==year)continue;const iso=d.toISOString().slice(0,10);if(showAll||workdayInfo(iso,workdays,bridgeDays,holidays).relevant)dates.push(iso);}return dates;}
export function employeeStatusForDate(entries:EmployeeAvailability[],assignments:EmployeeAssignment[],date:string,employeeId:string):CalendarStatusKey{const own=entriesForDate(entries,date,employeeId);if(own.some(e=>e.type==='Sonstige Abwesenheit'))return 'absence';if(own.some(e=>e.type==='Freiwunsch'&&e.status==='Genehmigt'))return 'timeOffApproved';if(own.some(e=>e.type==='Freiwunsch'&&e.status==='Abgelehnt'))return 'timeOffRejected';if(own.some(e=>e.type==='Freiwunsch'&&e.status==='Beantragt'))return 'timeOffOpen';if(assignments.some(a=>a.employeeId===employeeId&&a.date===date))return 'planned';if(own.some(e=>e.type==='Anwesend'))return 'present';return 'noResponse';}
export function monthSummary(year:number,month:number,employees:Employee[],availabilities:EmployeeAvailability[],assignments:EmployeeAssignment[],projects:Project[],workdays:WorkdayConfiguration[],bridgeDays:BridgeDay[],holidays:CompanyHolidayPeriod[]){const dates=relevantWorkdays(year,workdays,bridgeDays,holidays).filter(d=>new Date(`${d}T00:00:00Z`).getUTCMonth()===month);const capacities=dates.map(d=>calculateWorkforceCapacity(d,employees,availabilities,assignments,projects,3));return {month:monthNames[month],dates,workdays:dates.filter(d=>workdayInfo(d,workdays,bridgeDays,holidays).allowed).length,available:capacities.reduce((s,c)=>s+c.availableEmployees,0),shortages:capacities.filter(c=>c.missingEmployees>0).length,holidays:dates.filter(d=>workdayInfo(d,workdays,bridgeDays,holidays).status==='companyHoliday').length,blocked:dates.filter(d=>workdayInfo(d,workdays,bridgeDays,holidays).status==='blocked').length,openRequests:capacities.reduce((s,c)=>s+c.openTimeOffRequests,0)};}
export function splitDayPlanning(date:string,employees:Employee[],availabilities:EmployeeAvailability[],assignments:EmployeeAssignment[],projects:Project[],vehicles:Vehicle[]){const planned=assignments.filter(a=>a.date===date);const plannedIds=new Set(planned.map(a=>a.employeeId));return {available:employees.filter(e=>e.active&&employeeStatusForDate(availabilities,assignments,date,e.id)==='present'&&!plannedIds.has(e.id)),absent:employees.filter(e=>['absence','timeOffApproved'].includes(employeeStatusForDate(availabilities,assignments,date,e.id))),openRequests:employees.filter(e=>employeeStatusForDate(availabilities,assignments,date,e.id)==='timeOffOpen'),planned:employees.filter(e=>plannedIds.has(e.id)),vehicles:vehicles.filter(v=>v.status==='Verfügbar'||v.status==='Im Einsatz'),projects:projects.filter(p=>planned.some(a=>a.projectId===p.id)||p.plannedInstallationDate===date)};}
export function hasEmployeeHorizontalOverflow(css:string){return /employeeAvailability[\s\S]*overflow-x\s*:\s*hidden/.test(css)&&!/employeeYearCompact[\s\S]*365/.test(css);}
