import type {Employee,EmployeeAssignment,Project,User,Vehicle} from '../types';
export type EmployeeAvailabilityType='Anwesend'|'Freiwunsch'|'Sonstige Abwesenheit';
export type EmployeeAvailabilityStatus='Aktiv'|'Durch Admin geändert'|'Archiviert'|'Beantragt'|'Genehmigt'|'Abgelehnt'|'Durch Admin storniert'|'Gemeldet'|'Bestätigt';
export type DayPlanningStatus='Arbeitstag freigegeben'|'kein Arbeitstag'|'Betriebsferien'|'gesperrt'|'Sonderarbeitstag'|'noch nicht entschieden';
export type QualificationType='Teamleitung'|'Montage'|'Demontage'|'Aufmaß'|'Fundamente'|'Glasarbeiten'|'schwere Verglasung'|'Markisenmontage'|'ZIP-Screens'|'Lamellendächer'|'Carportmontage'|'Elektroanschluss LED'|'Motoren und Steuerungen'|'Service'|'Reparatur'|'Fahrzeugführung'|'Anhänger'|'Kranbedienung'|'Lager'|'sonstige Qualifikation';
export const QUALIFICATION_TYPES:QualificationType[]=['Teamleitung','Montage','Demontage','Aufmaß','Fundamente','Glasarbeiten','schwere Verglasung','Markisenmontage','ZIP-Screens','Lamellendächer','Carportmontage','Elektroanschluss LED','Motoren und Steuerungen','Service','Reparatur','Fahrzeugführung','Anhänger','Kranbedienung','Lager','sonstige Qualifikation'];
export interface AvailabilityAuditLog{ id:string; availabilityId:string; actorId:string; changedAt:string; reason:string; previousValue:string; newValue:string; }
export interface EmployeeAvailability{ id:string; employeeId:string; type:EmployeeAvailabilityType; subcategory?:string; startDate:string; endDate:string; allDay:boolean; startTime?:string; endTime?:string; status:EmployeeAvailabilityStatus; employeeNote:string; adminComment?:string; createdBy:string; createdAt:string; updatedBy:string; updatedAt:string; decidedBy?:string; decidedAt?:string; originalEntryId?:string; changeHistory:AvailabilityAuditLog[]; }
export interface AvailabilityChangeRequest{ id:string; availabilityId:string; employeeId:string; requestedChange:string; status:'Offen'|'Genehmigt'|'Abgelehnt'; createdAt:string; decidedBy?:string; decidedAt?:string; }
export interface WorkdayConfiguration{ id:string; date:string; status:DayPlanningStatus; workAllowed:boolean; label:string; adminNote:string; createdBy:string; createdAt:string; updatedBy?:string; updatedAt?:string; overrideReason?:string; }
export interface BridgeDay{ id:string; date:string; title:string; status:'Arbeitstag'|'frei'|'Betriebsferien'|'gesperrt'|'noch nicht entschieden'; workAllowed:boolean; note:string; createdBy:string; createdAt:string; }
export interface CompanyHolidayPeriod{ id:string; title:string; startDate:string; endDate:string; description:string; affectedTeamIds?:string[]; allEmployees:boolean; createdBy:string; createdAt:string; updatedBy?:string; updatedAt?:string; archived?:boolean; }
export interface EmployeeQualification{ id:string; employeeId:string; qualification:QualificationType; status:'Aktiv'|'In Ausbildung'|'Abgelaufen'|'Archiviert'; experienceLevel?:'Basis'|'Fortgeschritten'|'Experte'; validFrom:string; validUntil?:string; proofDocumentId?:string; note:string; }
export interface ProjectQualificationRequirement{ id:string; projectId:string; date:string; qualification:QualificationType; requiredCount:number; optional:boolean; }
export interface WorkforceConflict{ code:string; severity:'info'|'warning'|'blocking'; message:string; employeeId?:string; vehicleId?:string; projectId?:string; date:string; }
export interface WorkforceCapacity{ date:string; totalEmployees:number; present:number; absent:number; openTimeOffRequests:number; plannedEmployees:number; availableEmployees:number; plannedProjects:number; requiredEmployees:number; missingEmployees:number; }
export interface InternalNotification{ id:string; recipientRole?:'ADMIN'; recipientEmployeeId?:string; type:string; title:string; body:string; link:string; read:boolean; createdAt:string; }
export function isAdmin(user:Pick<User,'role'>){return user.role==='ADMIN'}
export function assertAvailabilityPermission(user:User,action:'readAll'|'manage'|'createOwn'|'approve'|'deleteOwn',employeeId?:string){if(isAdmin(user))return;if(action==='createOwn'&&employeeId===user.id)return;if(action==='deleteOwn')throw new Error('Mitarbeiter dürfen gespeicherte Verfügbarkeit nicht löschen.');throw new Error('Zugriff verweigert: Personalplanung');}
export function rangesOverlap(aStart:string,aEnd:string,bStart:string,bEnd:string){return aStart<=bEnd&&bStart<=aEnd}
export function entriesForDate(entries:EmployeeAvailability[],date:string,employeeId?:string){return entries.filter(e=>(!employeeId||e.employeeId===employeeId)&&rangesOverlap(e.startDate,e.endDate,date,date)&&e.status!=='Archiviert'&&e.status!=='Durch Admin storniert')}
export function createAvailability(entry:Omit<EmployeeAvailability,'id'|'createdAt'|'updatedAt'|'changeHistory'>,existing:EmployeeAvailability[],now=new Date()){if(entry.type==='Freiwunsch'){const hasPresence=existing.some(e=>e.employeeId===entry.employeeId&&e.type==='Anwesend'&&rangesOverlap(e.startDate,e.endDate,entry.startDate,entry.endDate)&&e.status!=='Archiviert');if(!hasPresence)throw new Error('Freiwunsch nur nach vorheriger Anwesenheit möglich.');}const iso=now.toISOString();return {...entry,id:`AV-${now.getTime()}`,createdAt:iso,updatedAt:iso,changeHistory:[]} }
export function decideTimeOff(entry:EmployeeAvailability,adminId:string,approved:boolean,comment:string,now=new Date()):EmployeeAvailability{if(entry.type!=='Freiwunsch')throw new Error('Nur Freiwünsche können entschieden werden.');return {...entry,status:approved?'Genehmigt':'Abgelehnt',adminComment:comment,decidedBy:adminId,decidedAt:now.toISOString(),updatedBy:adminId,updatedAt:now.toISOString(),changeHistory:[...entry.changeHistory,{id:`AUD-${now.getTime()}`,availabilityId:entry.id,actorId:adminId,changedAt:now.toISOString(),reason:comment||'Admin-Entscheidung',previousValue:entry.status,newValue:approved?'Genehmigt':'Abgelehnt'}]};}
export function isPlanningDayBlocked(date:string,workdays:WorkdayConfiguration[],bridgeDays:BridgeDay[],holidays:CompanyHolidayPeriod[]){const w=workdays.find(x=>x.date===date);const b=bridgeDays.find(x=>x.date===date);const holiday=holidays.find(h=>!h.archived&&rangesOverlap(h.startDate,h.endDate,date,date));const saturday=new Date(`${date}T00:00:00Z`).getUTCDay()===6;return Boolean(holiday)||w?.workAllowed===false||b?.workAllowed===false||(saturday&&!w?.workAllowed&&!b?.workAllowed);}
export function detectWorkforceConflicts(params:{date:string;projectId:string;employeeIds:string[];vehicleId?:string;requiredEmployees:number;requiredQualifications:ProjectQualificationRequirement[];availabilities:EmployeeAvailability[];assignments:EmployeeAssignment[];workdays:WorkdayConfiguration[];bridgeDays:BridgeDay[];companyHolidays:CompanyHolidayPeriod[];qualifications:EmployeeQualification[];}){const conflicts:WorkforceConflict[]=[];if(isPlanningDayBlocked(params.date,params.workdays,params.bridgeDays,params.companyHolidays))conflicts.push({code:'DAY_BLOCKED',severity:'blocking',message:'Tag ist durch Samstag-/Brückentag-/Betriebsferien-Regel nicht regulär planbar.',date:params.date,projectId:params.projectId});for(const employeeId of params.employeeIds){const entries=entriesForDate(params.availabilities,params.date,employeeId);if(!entries.some(e=>e.type==='Anwesend'))conflicts.push({code:'NOT_PRESENT',severity:'warning',message:'Mitarbeiter ist nicht als anwesend eingetragen.',employeeId,date:params.date});if(entries.some(e=>e.type==='Freiwunsch'&&e.status==='Beantragt'))conflicts.push({code:'OPEN_TIME_OFF',severity:'warning',message:'Offener Freiwunsch vorhanden.',employeeId,date:params.date});if(entries.some(e=>e.type==='Freiwunsch'&&e.status==='Genehmigt')||entries.some(e=>e.type==='Sonstige Abwesenheit'))conflicts.push({code:'UNAVAILABLE',severity:'blocking',message:'Mitarbeiter ist nicht verfügbar.',employeeId,date:params.date});if(params.assignments.some(a=>a.employeeId===employeeId&&a.date===params.date&&a.projectId!==params.projectId))conflicts.push({code:'DOUBLE_BOOKED',severity:'blocking',message:'Mitarbeiter ist bereits verplant.',employeeId,date:params.date});}
if(params.vehicleId&&params.assignments.some(a=>a.vehicleId===params.vehicleId&&a.date===params.date&&a.projectId!==params.projectId))conflicts.push({code:'VEHICLE_CONFLICT',severity:'blocking',message:'Fahrzeug ist bereits verplant.',vehicleId:params.vehicleId,date:params.date});
for(const req of params.requiredQualifications.filter(r=>r.projectId===params.projectId&&r.date===params.date)){const count=params.employeeIds.filter(id=>params.qualifications.some(q=>q.employeeId===id&&q.qualification===req.qualification&&q.status==='Aktiv')).length;if(count<req.requiredCount)conflicts.push({code:'MISSING_QUALIFICATION',severity:'warning',message:`Benötigte Qualifikation fehlt: ${req.qualification}.`,date:params.date,projectId:params.projectId});}return conflicts;}
export function calculateWorkforceCapacity(date:string,employees:Employee[],availabilities:EmployeeAvailability[],assignments:EmployeeAssignment[],projects:Project[],requiredEmployees:number):WorkforceCapacity{const entries=entriesForDate(availabilities,date);const planned=assignments.filter(a=>a.date===date);const presentIds=new Set(entries.filter(e=>e.type==='Anwesend').map(e=>e.employeeId));const absentIds=new Set(entries.filter(e=>e.type==='Sonstige Abwesenheit'||(e.type==='Freiwunsch'&&e.status==='Genehmigt')).map(e=>e.employeeId));return {date,totalEmployees:employees.filter(e=>e.active).length,present:presentIds.size,absent:absentIds.size,openTimeOffRequests:entries.filter(e=>e.type==='Freiwunsch'&&e.status==='Beantragt').length,plannedEmployees:new Set(planned.map(a=>a.employeeId)).size,availableEmployees:Math.max(0,presentIds.size-absentIds.size-new Set(planned.map(a=>a.employeeId)).size),plannedProjects:new Set(planned.map(a=>a.projectId)).size,requiredEmployees,missingEmployees:Math.max(0,requiredEmployees-Math.max(0,presentIds.size-absentIds.size-new Set(planned.map(a=>a.employeeId)).size))};}
export function sanitizeAvailabilityForUser(user:User,entry:EmployeeAvailability):EmployeeAvailability{if(isAdmin(user)||entry.employeeId===user.id)return entry;return {...entry,subcategory:undefined,employeeNote:'nicht verfügbar',adminComment:undefined};}
