'use client';
import React,{createContext,useContext,useEffect,useMemo,useState} from 'react';
import type {Appointment,Customer,Invoice,Offer,Project,Task} from './types';
import {demoProjects} from './models/demo-data';
import {PROJECT_STATUSES} from './types';
import {calculateOffer, changeOfferStatus, createEmptyOffer, duplicateOffer, integrateOfferIntoProjects} from './models/offer-engine';
import {LEGACY_STORAGE_KEY_V07,PERSISTENCE_SCHEMA_VERSION,STORAGE_KEY_V09,createProjectNumber,updateProjectBaseData} from './models/project-helpers';

export type {Appointment,Customer,Invoice,Offer,Project,Task} from './types';
export type Supplier={id:string,name:string,category:string,contact:string};
export type Entry={id:string,date:string,type:'Einnahme'|'Ausgabe',category:string,text:string,net:number,vat:number,paid:boolean};
export type TaxEvent={id:string,date:string,type:string,amount:number,status:string,note:string};
export type CalcItem={id:string;supplier:string;description:string;quantity:number;purchaseNet:number;rule:string;customFactor:number;transportFactor:number;assemblyNet:number;otherNet:number;vatRate:number};
export type Calculation={id:string;number:string;customer:string;project:string;createdAt:string;status:string;notes:string;items:CalcItem[]};
export type Settings={revenuePlan:number;taxReserve:number;cashStart:number};
export type State={schemaVersion:number;customers:Customer[];offers:Offer[];projects:Project[];suppliers:Supplier[];entries:Entry[];tasks:Task[];appointments:Appointment[];invoices:Invoice[];taxEvents:TaxEvent[];calculations:Calculation[];settings:Settings};
type CollectionKey={ [K in keyof State]: State[K] extends Array<unknown> ? K : never }[keyof State];
type ProjectBaseUpdate = Pick<Project, 'status' | 'phase' | 'priority' | 'responsible' | 'montage'>;
type Api={state:State;setState:React.Dispatch<React.SetStateAction<State>>;add:<K extends CollectionKey>(key:K,item:State[K][number] | Record<string, unknown>)=>void;update:<K extends CollectionKey>(key:K,id:string,item:State[K][number] | Record<string, unknown>)=>void;updateProjectBase:(id:string, item:ProjectBaseUpdate)=>void;createOffer:(projectId:string)=>void;saveOffer:(offer:Offer)=>void;duplicateOffer:(id:string)=>void;changeOfferStatus:(id:string,status:Offer['status'],user:string)=>void;remove:(key:CollectionKey,id:string)=>void;reset:()=>void;exportData:()=>void};

export const initial:State={
 schemaVersion:PERSISTENCE_SCHEMA_VERSION,
 customers:[{id:'K-1001',name:'OBI Beispielkunde Nord',email:'',phone:'',city:'',status:'Aktiv'},{id:'K-1002',name:'Beispielkunde Süd',email:'',phone:'',city:'',status:'Aktiv'},{id:'K-1003',name:'Musterkunde',email:'',phone:'',city:'',status:'Aktiv'}],
 offers:[{id:'AG20260001-V1',offerNumber:'AG20260001',version:1,customer:'OBI Beispielkunde Nord',title:'Pultdach + Markise',net:20882.35,gross:24849.9965,status:'Versendet',date:'2026-05-09',editor:'Kastonia Team',items:[],calculation:{net:20882.35,gross:24850,vat:3967.65,discount:0,material:20882.35,assembly:0,delivery:0,other:0,contributionMargin:0,marginAmount:0,marginPercent:0,projectProfit:0},statusHistory:[]}],
 projects:demoProjects,
 suppliers:[{id:'L-01',name:'MB Veranda',category:'Terrassendächer',contact:''},{id:'L-02',name:'Lewens',category:'Markisen',contact:''},{id:'L-03',name:'SELT',category:'Sonnenschutz',contact:''},{id:'L-04',name:'Stores Marquises',category:'Lamellendächer',contact:''},{id:'L-05',name:'PF Gruppe',category:'Carports',contact:''},{id:'L-06',name:'Sonstiges',category:'Zubehör / Fremdleistung',contact:''}],
 entries:[{id:'E-1',date:'2026-07-01',type:'Einnahme',category:'Umsatz',text:'Kundenrechnungen',net:128440,vat:24403.6,paid:true},{id:'A-1',date:'2026-07-05',type:'Ausgabe',category:'Wareneinsatz',text:'Lieferanten',net:66420,vat:12619.8,paid:true},{id:'A-2',date:'2026-07-10',type:'Ausgabe',category:'Betriebskosten',text:'Laufende Kosten',net:19840,vat:3769.6,paid:true}],
 tasks:[{id:'T1',title:'Musterangebot überarbeiten',due:'2026-07-20',priority:'Hoch',done:false},{id:'T2',title:'OBI-Leads nachfassen',due:'2026-07-21',priority:'Hoch',done:false},{id:'T3',title:'Musterprojekt Senkrechtmarkise aufmessen',due:'2026-07-22',priority:'Mittel',done:false}],
 appointments:[{id:'KA1',title:'Aufmaß Musterkunde',date:'2026-07-20',type:'Aufmaß'},{id:'KA2',title:'Mustertermin',date:'2026-07-23',type:'Kundentermin'},{id:'KA3',title:'Montage Musterkunde',date:'2026-07-27',type:'Montage'}],
 invoices:[{id:'R1',direction:'Ausgang',number:'RE12763',partner:'Musterkunde',project:'Terrassendach',date:'2026-05-02',due:'2026-07-30',net:6550,vatRate:19,status:'Offen'},{id:'R2',direction:'Eingang',number:'ER-2026-44',partner:'Lewens',project:'Musterprojekt',date:'2026-07-12',due:'2026-08-05',net:4200,vatRate:19,status:'Offen'},{id:'R3',direction:'Eingang',number:'2026/4/070228',partner:'Aluprof',project:'Musterprojekt',date:'2026-07-20',due:'2026-08-03',net:1793.30,vatRate:0,status:'Offen'}],
 taxEvents:[{id:'S1',date:'2026-08-14',type:'ESt-Nachzahlung 2024',amount:10162.48,status:'Offen',note:''},{id:'S2',date:'2026-08-15',type:'Gewerbesteuer',amount:435,status:'Offen',note:'Quartalszahlung'},{id:'S3',date:'2026-08-20',type:'Gewerbesteuer Nachzahlung',amount:2616,status:'Offen',note:''},{id:'S4',date:'2026-09-10',type:'USt-VA Juli 2026',amount:1680.32,status:'Offen',note:''},{id:'S5',date:'2026-11-15',type:'Gewerbesteuer',amount:435,status:'Offen',note:'Quartalszahlung'}],
 calculations:[],settings:{revenuePlan:420000,taxReserve:46448,cashStart:18420}
};

type LegacyProject = Partial<Omit<Project, 'status'>> & {id:string;customer?:string;title?:string;value?:number;status?:string;montage?:string};
export function normalizeProject(raw:LegacyProject, index=0):Project{
 const now=new Date().toISOString();
 const legacyStatusMap: Record<string, Project['status']> = {'Lead':'Neue Anfrage','Angebot':'Angebot in Vorbereitung','Auftrag':'Auftrag erhalten','Material bestellt':'Bestellung Lieferant','Rechnung offen':'Rechnung gestellt'};
 const mappedStatus = raw.status && PROJECT_STATUSES.includes(raw.status as Project['status']) ? raw.status as Project['status'] : legacyStatusMap[raw.status || ''] || 'Neue Anfrage';
 const base: Project = {projectNumber:raw.projectNumber||createProjectNumber(new Date(),index+1),title:raw.title||'Unbenanntes Projekt',customer:raw.customer||'Unbekannt',contactPersons:raw.contactPersons||[],projectAddress:raw.projectAddress||{street:'',postalCode:'',city:'',country:'DE'},billingAddress:raw.billingAddress||{street:'',postalCode:'',city:'',country:'DE'},leadSource:raw.leadSource||'Sonstiges',isObiLead:raw.isObiLead||false,projectType:raw.projectType||'Sonstiges',status:mappedStatus,phase:raw.phase||'Lead',priority:raw.priority||'Mittel',responsible:raw.responsible||'',createdAt:raw.createdAt||now,updatedAt:raw.updatedAt||now,measurements:raw.measurements||[],offers:raw.offers||[],orderConfirmations:raw.orderConfirmations||[],supplierOrders:raw.supplierOrders||[],installations:raw.installations||[],invoices:raw.invoices||[],payments:raw.payments||[],documents:raw.documents||[],notes:raw.notes||[],communication:raw.communication||[],tasks:raw.tasks||[],appointments:raw.appointments||[],financials:raw.financials||{currency:'EUR',expectedRevenueNet:raw.value||0,expectedRevenueGross:raw.value||0,expectedCostNet:0,expectedCostGross:0,customerPaid:0,supplierPaid:0},tags:raw.tags||[],archived:raw.archived||false,value:raw.value||raw.financials?.expectedRevenueGross||0,montage:raw.montage||raw.installations?.[0]?.plannedStart||'',id:raw.id};
 return {...base,...raw,status:mappedStatus,value:base.value,montage:base.montage};
}
export function migrateToV09(raw:unknown):State{const parsed=typeof raw==='string'?JSON.parse(raw):raw;if(!parsed||typeof parsed!=='object')throw new Error('Invalid persisted state');const legacy=parsed as Partial<State>;return {...initial,...legacy,schemaVersion:PERSISTENCE_SCHEMA_VERSION,offers:(legacy.offers||initial.offers).map((offer)=>{const base=offer as Partial<Offer> & {id:string;status?:string;net?:number;gross?:number};const legacyStatus=base.status as string | undefined;const offerNumber=base.offerNumber||base.id;const items=base.items||[];const calculation=base.calculation||calculateOffer(items);return {...base,offerNumber,version:base.version||1,status:(legacyStatus==='Auftrag'?'Gewonnen':legacyStatus==='Abgelehnt'?'Verloren':legacyStatus||'Entwurf') as Offer['status'],gross:base.gross||calculation.gross,net:base.net||calculation.net,editor:base.editor||'Kastonia Team',items,calculation,statusHistory:base.statusHistory||[]} as Offer;}),projects:(legacy.projects||initial.projects).map((p,index)=>normalizeProject(p as Parameters<typeof normalizeProject>[0],index))};}
export function loadPersistedState(storage:Pick<Storage,'getItem'>):State{const current=storage.getItem(STORAGE_KEY_V09);if(current)return migrateToV09(current);const legacy=storage.getItem(LEGACY_STORAGE_KEY_V07);if(legacy)return migrateToV09(legacy);return initial;}
const C=createContext<Api|null>(null);
export function StoreProvider({children}:{children:React.ReactNode}){const [state,setState]=useState<State>(initial);useEffect(()=>{try{setState(loadPersistedState(localStorage))}catch(error){console.warn('KASTONIA ERP migration failed; existing localStorage data was left untouched.',error)}},[]);useEffect(()=>{try{localStorage.setItem(STORAGE_KEY_V09,JSON.stringify(state))}catch{}},[state]);const api=useMemo<Api>(()=>({state,setState,add:(key,item)=>setState(s=>({...s,[key]:[...(s[key] as unknown[]),item]})),update:(key,id,item)=>setState(s=>({...s,[key]:(s[key] as Array<{id:string}>).map(x=>x.id===id?item:x)})),updateProjectBase:(id,item)=>setState(s=>({...s,projects:s.projects.map(project=>project.id===id?updateProjectBaseData(project,item):project)})),createOffer:(projectId)=>setState(s=>{const project=s.projects.find(p=>p.id===projectId);if(!project)return s;const offer=createEmptyOffer(project,s.offers);return {...s,offers:[...s.offers,offer],projects:integrateOfferIntoProjects(s.projects,offer)};}),saveOffer:(offer)=>setState(s=>{const calculation=calculateOffer(offer.items);const saved={...offer,net:calculation.net,gross:calculation.gross,calculation};const offers=s.offers.some(o=>o.id===saved.id)?s.offers.map(o=>o.id===saved.id?saved:o):[...s.offers,saved];return {...s,offers,projects:integrateOfferIntoProjects(s.projects,saved)};}),duplicateOffer:(id)=>setState(s=>{const offer=s.offers.find(o=>o.id===id);if(!offer)return s;const copy=duplicateOffer(offer,s.offers);return {...s,offers:[...s.offers,copy],projects:integrateOfferIntoProjects(s.projects,copy)};}),changeOfferStatus:(id,status,user)=>setState(s=>{const offer=s.offers.find(o=>o.id===id);if(!offer)return s;const updated=changeOfferStatus(offer,status,user);return {...s,offers:s.offers.map(o=>o.id===id?updated:o),projects:integrateOfferIntoProjects(s.projects,updated)};}),remove:(key,id)=>setState(s=>({...s,[key]:(s[key] as Array<{id:string}>).filter(x=>x.id!==id)})),reset:()=>setState(initial),exportData:()=>{const b=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download='KASTONIA_ERP_Backup_v09.json';a.click();URL.revokeObjectURL(u)}}),[state]);return <C.Provider value={api}>{children}</C.Provider>}
export const useStore=()=>{const store=useContext(C);if(!store)throw new Error('useStore must be used within StoreProvider');return store};
export const eur=(n:number)=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n||0);
