'use client';
import Shell from '../../components/Shell';
import {CalcItem,Calculation,eur,useStore} from '../../lib/store';
import {useMemo,useState} from 'react';

const emptyItem=():CalcItem=>({id:crypto.randomUUID(),supplier:'MB Veranda',description:'',quantity:1,purchaseNet:0,rule:'auto',customFactor:2.9,transportFactor:1.1,assemblyNet:0,otherNet:0,vatRate:19});
function mbFactor(ek:number){if(ek>=6000)return 2.5;if(ek>=5000)return 2.6;if(ek>=4000)return 2.7;if(ek>=3000)return 2.8;return 2.9}
function calc(item:CalcItem){
 const qty=Math.max(1,Number(item.quantity)||1); const ek=(Number(item.purchaseNet)||0)*qty; let sale=0;
 if(item.rule==='mb') sale=ek*mbFactor(ek);
 else if(item.rule==='lewens40') sale=ek/0.60;
 else if(item.rule==='lewens45') sale=ek/0.55;
 else if(item.rule==='lamella50') sale=ek/0.50;
 else if(item.rule==='other100') sale=ek*2;
 else sale=ek*(Number(item.customFactor)||1);
 const transport=ek*Math.max(0,(Number(item.transportFactor)||1)-1);
 const cost=ek+transport+(Number(item.assemblyNet)||0)+(Number(item.otherNet)||0);
 const net=sale+(Number(item.assemblyNet)||0)+(Number(item.otherNet)||0)+transport;
 const vat=net*(Number(item.vatRate)||0)/100; const gross=net+vat; const profit=net-cost;
 return {ek,transport,cost,net,vat,gross,profit,margin:net?profit/net*100:0};
}
export default function Page(){
 const {state,add}=useStore(); const [customer,setCustomer]=useState(''); const [project,setProject]=useState(''); const [notes,setNotes]=useState(''); const [items,setItems]=useState<CalcItem[]>([emptyItem()]);
 const totals=useMemo(()=>items.map(calc).reduce((a,x)=>({ek:a.ek+x.ek,cost:a.cost+x.cost,net:a.net+x.net,vat:a.vat+x.vat,gross:a.gross+x.gross,profit:a.profit+x.profit}),{ek:0,cost:0,net:0,vat:0,gross:0,profit:0}),[items]);
 const margin=totals.net?totals.profit/totals.net*100:0;
 const set=(id:string,key:keyof CalcItem,value:any)=>setItems(v=>v.map(x=>x.id===id?{...x,[key]:value}:x));
 const save=(status='Entwurf')=>{if(!customer||!project){alert('Bitte Kunde und Projektbezeichnung ausfüllen.');return}const c:Calculation={id:crypto.randomUUID(),number:'KALK-'+new Date().getFullYear()+'-'+String(state.calculations.length+1).padStart(4,'0'),customer,project,createdAt:new Date().toISOString(),status,notes,items};add('calculations',c);alert(status==='An Seda übergeben'?'Kalkulation gespeichert und für Seda markiert.':'Kalkulation gespeichert.');setCustomer('');setProject('');setNotes('');setItems([emptyItem()]);};
 return <Shell><div className="pageHead"><div><p className="eyebrow">INTERNE ANGEBOTSVORBEREITUNG</p><h1>Kalkulation zusammenstellen</h1><p>Keine offizielle Angebotserstellung. Hier bereitest du intern Kosten, Verkauf, Steuer und Gewinn für Seda vor.</p></div></div>
 <article className="panel"><div className="formGrid"><label>Kunde<select value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">Kunde wählen</option>{state.customers.map((x:any)=><option key={x.id}>{x.name}</option>)}</select></label><label>Projekt / Bezeichnung<input value={project} onChange={e=>setProject(e.target.value)} placeholder="z. B. Cube 6 x 3,5 m + ZIP"/></label><label className="full">Interne Hinweise für Seda<input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Farbe, Maße, Sonderwünsche, Rabatte, Lieferzeit ..."/></label></div></article>
 <article className="panel"><div className="panelHead"><h2>Positionen</h2><button className="primary" onClick={()=>setItems(v=>[...v,emptyItem()])}>+ Position</button></div><div className="calcTableWrap"><table className="calcTable"><thead><tr><th>Lieferant</th><th>Beschreibung</th><th>Menge</th><th>EK netto</th><th>Regel</th><th>Faktor</th><th>Transport</th><th>Montage</th><th>Sonstiges</th><th>USt</th><th>VK netto</th><th>Gewinn</th><th></th></tr></thead><tbody>{items.map(item=>{const r=calc(item);return <tr key={item.id}><td><select value={item.supplier} onChange={e=>set(item.id,'supplier',e.target.value)}>{state.suppliers.map((x:any)=><option key={x.id}>{x.name}</option>)}</select></td><td><input value={item.description} onChange={e=>set(item.id,'description',e.target.value)} placeholder="Produkt / Leistung"/></td><td><input type="number" min="1" value={item.quantity} onChange={e=>set(item.id,'quantity',+e.target.value)}/></td><td><input type="number" value={item.purchaseNet||''} onChange={e=>set(item.id,'purchaseNet',+e.target.value)}/></td><td><select value={item.rule} onChange={e=>set(item.id,'rule',e.target.value)}><option value="mb">MB Staffel</option><option value="lewens40">Lewens 40 % Profit</option><option value="lewens45">Lewens Senkrecht 45 %</option><option value="lamella50">Lamellendach 50 %</option><option value="other100">Sonstiges 100 % Aufschlag</option><option value="auto">Eigener Faktor</option></select></td><td><input type="number" step="0.1" value={item.rule==='mb'?mbFactor(item.purchaseNet*item.quantity):item.customFactor} disabled={item.rule!=='auto'} onChange={e=>set(item.id,'customFactor',+e.target.value)}/></td><td><input type="number" step="0.1" value={item.transportFactor} onChange={e=>set(item.id,'transportFactor',+e.target.value)}/></td><td><input type="number" value={item.assemblyNet||''} onChange={e=>set(item.id,'assemblyNet',+e.target.value)}/></td><td><input type="number" value={item.otherNet||''} onChange={e=>set(item.id,'otherNet',+e.target.value)}/></td><td><select value={item.vatRate} onChange={e=>set(item.id,'vatRate',+e.target.value)}><option value="19">19 %</option><option value="7">7 %</option><option value="0">0 %</option><option value="16">16 % historisch</option><option value="5">5 % historisch</option></select></td><td><b>{eur(r.net)}</b></td><td><b className={r.profit<0?'negative':'positive'}>{eur(r.profit)}</b><small>{r.margin.toFixed(1)} %</small></td><td><button className="ghost" onClick={()=>setItems(v=>v.filter(x=>x.id!==item.id))}>Entfernen</button></td></tr>})}</tbody></table></div></article>
 <section className="summaryGrid"><article className="panel result"><small>Material-EK netto</small><strong>{eur(totals.ek)}</strong><div><span>Gesamtkosten netto</span><b>{eur(totals.cost)}</b></div></article><article className="panel result"><small>Verkauf netto</small><strong>{eur(totals.net)}</strong><div><span>Umsatzsteuer</span><b>{eur(totals.vat)}</b></div><div><span>Verkauf brutto</span><b>{eur(totals.gross)}</b></div></article><article className="panel result"><small>Gewinn netto</small><strong>{eur(totals.profit)}</strong><div><span>Marge</span><b>{margin.toFixed(1)} %</b></div></article></section>
 <article className="panel actionBar"><div><b>Interner Ablauf</b><p>Speichern → prüfen → an Seda übergeben → Seda erstellt daraus das offizielle AG.</p></div><div className="actions"><button className="ghostBtn" onClick={()=>window.print()}>Drucken / PDF</button><button className="ghostBtn" onClick={()=>save('Entwurf')}>Als Entwurf speichern</button><button className="primary" onClick={()=>save('An Seda übergeben')}>An Seda übergeben</button></div></article>
 </Shell>}
