'use client';
import Shell from '../../components/Shell';
import {useMemo,useState} from 'react';
import {useStore,type EmployeeAssignment} from '../../lib/store';
import {calculateWorkforceCapacity,detectWorkforceConflicts,entriesForDate,QUALIFICATION_TYPES} from '../../lib/models/workforce-availability';

const relevantDays=['2026-05-15','2026-07-22','2026-07-23','2026-07-24','2026-10-10','2026-12-24'];
const requiredEmployees=3;
const iconPaths={check:<path d="M5 12l4 4L19 6"/>,brief:<><rect x="4" y="7" width="16" height="11" rx="2"/><path d="M9 7V5h6v2M4 12h16"/></>,truck:<><path d="M3 7h11v10H3zM14 11h4l3 3v3h-7z"/><circle cx="7" cy="18" r="2"/><circle cx="17" cy="18" r="2"/></>,tool:<path d="M14 7l3-3 3 3-3 3M4 20l9-9M11 5l8 8"/>,box:<><path d="M4 7l8-4 8 4-8 4z"/><path d="M4 7v10l8 4 8-4V7M12 11v10"/></>,userPlus:<><path d="M15 19a6 6 0 00-12 0"/><circle cx="9" cy="8" r="4"/><path d="M19 8v6M16 11h6"/></>,userMinus:<><path d="M15 19a6 6 0 00-12 0"/><circle cx="9" cy="8" r="4"/><path d="M16 11h6"/></>,crown:<><path d="M4 8l4 4 4-7 4 7 4-4v11H4z"/><path d="M4 19h16"/></>};
type IconName=keyof typeof iconPaths;
function Icon({name}:{name:IconName}){return <svg className="uiIcon" viewBox="0 0 24 24" aria-hidden="true" focusable="false">{iconPaths[name]}</svg>;}
function dateLabel(date:string){return new Intl.DateTimeFormat('de-DE',{weekday:'long',day:'2-digit',month:'2-digit'}).format(new Date(`${date}T00:00:00Z`));}
function bar(current:number,total:number){const pct=total?Math.min(100,Math.round(current/total*100)):0;return <div className="capacityBar" aria-label={`${current} von ${total}`}><span style={{width:`${pct}%`}}/></div>;}

export default function EinsatzplanungPage(){
 const {state,add,remove,update}=useStore();
 const [focus,setFocus]=useState('2026-07-22');
 const [projectId,setProjectId]=useState('P-003');
 const [dragged,setDragged]=useState<string|null>(null);
 const [note,setNote]=useState('');
 const projects=state.projects.slice(0,4);
 const focusProject=state.projects.find(p=>p.id===projectId)||state.projects[0];
 const focusAssignments=state.employeeAssignments.filter(a=>a.date===focus&&a.projectId===focusProject.id);
 const allDayAssignments=state.employeeAssignments.filter(a=>a.date===focus);
 const capacity=calculateWorkforceCapacity(focus,state.employees,state.employeeAvailabilities,allDayAssignments,state.projects,requiredEmployees);
 const available=state.employees.filter(e=>e.active&&entriesForDate(state.employeeAvailabilities,focus,e.id).some(a=>a.type==='Anwesend'));
 const unassigned=available.filter(e=>!focusAssignments.some(a=>a.employeeId===e.id));
 const team=focusAssignments.map(a=>({assignment:a,employee:state.employees.find(e=>e.id===a.employeeId)}));
 const conflicts=detectWorkforceConflicts({date:focus,projectId:focusProject.id,employeeIds:focusAssignments.map(a=>a.employeeId),vehicleId:'FZG-001',requiredEmployees,requiredQualifications:state.projectQualificationRequirements,availabilities:state.employeeAvailabilities,assignments:state.employeeAssignments,workdays:state.workdayConfigurations,bridgeDays:state.bridgeDays,companyHolidays:state.companyHolidayPeriods,qualifications:state.employeeQualifications});
 const saved=useMemo(()=>`Letzte Speicherung: ${focusAssignments.length} Teammitglieder für ${dateLabel(focus)}`,[focusAssignments.length,focus]);
 function assignEmployee(employeeId:string){if(!employeeId||focusAssignments.some(a=>a.employeeId===employeeId))return;const entry:EmployeeAssignment={id:`EA-${Date.now()}`,projectId:focusProject.id,montageId:'M-001',employeeId,date:focus,startTime:'08:00',plannedEndTime:'16:30',teamRole:'Montage',teamLead:focusAssignments.length===0,vehicleId:'FZG-001',note};add('employeeAssignments',entry);setNote('');}
 function approvePlan(){focusAssignments.forEach(a=>update('employeeAssignments',a.id,{...a,note:[a.note,'Plan genehmigt'].filter(Boolean).join(' · ')}));}
 return <Shell><div className="pageHead"><div><p className="eyebrow">OPERATIONS · EINSATZPLANUNG</p><h1>Projektzentrierte Einsatzplanung</h1><p>Drag & Drop, Mehrfachauswahl, Teamzuweisung und genehmigungsfähige Einsatzpläne für Mobile, Tablet und Desktop; berücksichtigt freigegebene Samstage, Brückentage, Sonderarbeitstage und Betriebsferien.</p></div><button className="primary" onClick={approvePlan}>Plan genehmigen</button></div>
 <section className="planningViews" aria-label="Filter Einsatzplanung"><select value={projectId} onChange={e=>setProjectId(e.target.value)}>{projects.map(p=><option value={p.id} key={p.id}>{p.title}</option>)}</select><select value={focus} onChange={e=>setFocus(e.target.value)}>{relevantDays.map(d=><option value={d} key={d}>{dateLabel(d)}</option>)}</select><span>Team</span><span>Fahrzeug FZG-001</span><span>Qualifikation</span></section>
 <section className="panel"><div className="panelHead"><h2>Monatsübersicht · relevante Arbeitstage</h2><span className="chip">{saved}</span></div><div className="projectMonthList">{relevantDays.map((d,i)=>{const project=projects[i%projects.length];const planned=state.employeeAssignments.filter(a=>a.date===d&&a.projectId===project?.id).length;const holiday=state.companyHolidayPeriods.some(h=>h.startDate<=d&&h.endDate>=d);return <button className="projectDayCard" key={d} onClick={()=>{setFocus(d);if(project)setProjectId(project.id);}}><div><time>{dateLabel(d)}</time><h3>{holiday?'Betriebsferien':project?.title||'Noch kein Projekt'}</h3><p>{holiday?'Keine Einsatzplanung':`${project?.customer} · ${project?.projectAddress.street}, ${project?.projectAddress.city}`}</p></div>{!holiday&&<div className="projectDayMeta"><span className={`statusChip ${planned<requiredEmployees?'wait':'ok'}`}>{planned<requiredEmployees?'⚠':'✓'} {planned} / {requiredEmployees} Mitarbeiter</span><span><Icon name="truck"/> Sprinter 1</span></div>}</button>})}</div></section>
 <section className="planningDetail"><article className="panel"><h2>{focusProject.title}</h2><div className="detailGrid"><p><b>Kunde</b>{focusProject.customer}</p><p><b>Adresse</b>{focusProject.projectAddress.street}, {focusProject.projectAddress.city}</p><p><b>Datum</b>{dateLabel(focus)}</p><p><b>Beginn</b>08:00</p><p><b>Ende</b>16:30</p><p><b>Fahrzeug</b>Sprinter 1 · FZG-001</p><p><b>Werkzeuge</b><span className="statusChip ok"><Icon name="tool"/> vollständig</span></p><p><b>Material</b><span className="statusChip wait"><Icon name="box"/> teilweise vorhanden</span></p><p><b>Geplante Stunden</b>8 h je Monteur</p></div><div className="capacityPanel"><div><b>Personal</b>{bar(capacity.present,capacity.totalEmployees)}<small>{capacity.present} von {capacity.totalEmployees} verfügbar</small></div><div><b>Projektbedarf</b>{bar(focusAssignments.length,requiredEmployees)}<small>{focusAssignments.length} von {requiredEmployees} eingeplant</small></div></div>{conflicts.map(c=><p className="alertRow" key={c.code}>{c.severity==='blocking'?'⛔':'⚠'} {c.message}</p>)}</article><article className="panel"><h2>Projektstatus</h2><p><b>Benötigt:</b> {requiredEmployees} Monteure</p><p><b>Geplant:</b> {focusAssignments.length}</p><p><span className="statusChip wait">⚠ {Math.max(0,requiredEmployees-focusAssignments.length)} fehlt</span></p><label>Planungsnotiz<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Hinweis für Team, Material oder Anfahrt"/></label><button className="primary wide" onClick={()=>alert('Einsatzplan gespeichert')}>Speichern</button></article></section>
 <section className="assignmentColumns"><article className="panel"><h2>Verfügbare Mitarbeiter</h2>{unassigned.map(e=>{const q=state.employeeQualifications.filter(x=>x.employeeId===e.id&&x.status==='Aktiv');return <button className="employeeAssignCard" draggable onDragStart={()=>setDragged(e.id)} onClick={()=>assignEmployee(e.id)} key={e.id}><b>{e.name}</b><span className="statusChip ok"><Icon name="check"/> Anwesend</span><span>Tippen oder ziehen zum Zuweisen</span><div className="qualBadges">{q.map(x=><span key={x.id}>✓ {x.qualification}</span>)}{QUALIFICATION_TYPES.slice(1,3).map(x=><span className="mutedBadge" key={x}>✖ {x}</span>)}</div></button>})}</article><article className="panel dropZone" onDragOver={e=>e.preventDefault()} onDrop={()=>dragged&&assignEmployee(dragged)}><h2>Projektteam</h2>{team.map(({assignment,employee})=><div className="employeeAssignCard team" key={assignment.id}><b>{employee?.name}</b><span className="statusChip info"><Icon name="brief"/> {assignment.teamLead?'Teamleiter':'Montage'}</span><span>{employee?.driverLicenseClass?'Fahrzeugführer':'kein Fahrer'}</span><div className="actions"><button onClick={()=>update('employeeAssignments',assignment.id,{...assignment,teamLead:true})}><Icon name="crown"/> Teamleiter</button><button onClick={()=>remove('employeeAssignments',assignment.id)}><Icon name="userMinus"/> Entfernen</button></div></div>)}<select onChange={e=>assignEmployee(e.target.value)} defaultValue=""><option value="">Mehrfachauswahl: Mitarbeiter auswählen …</option>{unassigned.map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select><p className="muted">Drag & Drop, Auswahlfeld und Antippen funktionieren auf Desktop, Tablet und Mobilgerät.</p></article></section>
 </Shell>;
}
