-- KASTONIA ERP v1.8 Cloud Foundation: Supabase PostgreSQL, Auth profiles, Storage metadata and RLS.
do $$ begin create type public.user_role as enum ('ADMIN','MITARBEITER'); exception when duplicate_object then null; end $$;
create table if not exists public.user_profiles (id uuid primary key references auth.users(id) on delete cascade, name text not null, email text not null unique, role public.user_role not null default 'MITARBEITER', employee_id text, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), last_sign_in_at timestamptz);
create table if not exists public.erp_records (id text primary key, collection text not null, payload jsonb not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.file_assets (id uuid primary key default gen_random_uuid(), project_id text, site_id text, message_id text, user_id uuid references auth.users(id), category text not null, file_name text not null, file_type text not null, file_size bigint not null check (file_size <= 15728640), storage_path text not null unique, description text, captured_or_uploaded_at timestamptz not null default now(), created_at timestamptz not null default now());
create table if not exists public.migration_runs (id uuid primary key default gen_random_uuid(), started_by uuid references auth.users(id), dry_run boolean not null, status text not null, result jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create or replace function public.current_user_role() returns text language sql stable security definer set search_path=public as $$ select role::text from public.user_profiles where id=auth.uid() and active=true $$;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select coalesce(public.current_user_role()='ADMIN',false) $$;
alter table public.user_profiles enable row level security; alter table public.erp_records enable row level security; alter table public.file_assets enable row level security; alter table public.migration_runs enable row level security;
drop policy if exists admin_all_profiles on public.user_profiles; create policy admin_all_profiles on public.user_profiles for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists own_profile on public.user_profiles; create policy own_profile on public.user_profiles for select using (id=auth.uid() and active=true);
drop policy if exists admin_all_records on public.erp_records; create policy admin_all_records on public.erp_records for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists employee_safe_records on public.erp_records; create policy employee_safe_records on public.erp_records for select using (public.current_user_role()='MITARBEITER' and collection in ('projects','employeeAssignments','workTimeEntries','siteMessages','tools','vehicles','notifications'));
drop policy if exists admin_all_files on public.file_assets; create policy admin_all_files on public.file_assets for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists employee_own_files on public.file_assets; create policy employee_own_files on public.file_assets for select using (user_id=auth.uid());
drop policy if exists employee_insert_own_files on public.file_assets; create policy employee_insert_own_files on public.file_assets for insert with check (user_id=auth.uid());
drop policy if exists admin_migrations on public.migration_runs; create policy admin_migrations on public.migration_runs for all using (public.is_admin()) with check (public.is_admin());
