'use client';
import Shell from '../../components/Shell';
import {useStore} from '../../lib/store';
import {buildCalendarEvents, materialCheckForProject, todayWorkload} from '../../lib/models/operations-center';

const today=()=>new Date().toISOString().slice(0,10);
export default function TodayPage(){
 const {state}=useStore(); const date=today();
 const tasks=state.tasks.map(task=>({...task,description:task.description||'',project:task.project||'',customer:task.customer||'',responsible:task.responsible||'',status:task.status||(!task.done?'Offen':'Erledigt'),category:task.category||'Sonstiges',attachments:task.attachments||[],comments:task.comments||[]}));
 const work=todayWorkload({date,projects:state.projects,appointments:state.appointments,tasks,offers:state.offers,purchaseOrders:state.purchaseOrders,deliveries:state.deliveries,invoices:state.invoices,siteReports:state.siteReports});
 const events=buildCalendarEvents(state.appointments,state.deliveries,state.projects).filter(event=>event.date===date);
 const kpis=[['Heutige Montagen',work.installations.length],['Kundentermine',work.customerAppointments.length],['Rückrufe offen',work.callbacks.length],['Angebote offen',work.openOffers.length],['Bestellungen offen',work.openPurchaseOrders.length],['Rechnungen offen',work.openInvoices.length]] as const;
 return <Shell><div className="pageHead"><div><p className="eyebrow">OPERATIONS CENTER</p><h1>Heute</h1><p>Zentrale Tagessteuerung für Montage, Kunden, Einkauf, Material und Rechnungen.</p></div><a className="primary" href="/montageplanung">Montage planen</a></div><section className="cockpitKpis">{kpis.map(([label,value])=><article className="kpiCard" key={label}><small>{label}</small><strong>{value}</strong><span>direkt aus bestehenden ERP-Modulen</span></article>)}</section><section className="twoCol"><article className="panel"><div className="panelHead"><h2>Direkt anklickbare Einträge</h2><a href="/kalender">Kalender</a></div>{events.map(event=><a className="alertRow" href={event.href} key={event.id}><b>{event.title}</b><span>{event.type} · {new Date(event.date).toLocaleDateString('de-DE')}</span></a>)}{work.openSiteReports.map(report=><a className="alertRow" href="/baustellenmeldungen" key={report.id}><b>{report.title}</b><span>{report.category} · {report.status}</span></a>)}{work.openInvoices.slice(0,5).map(invoice=><a className="alertRow" href="/rechnungen" key={invoice.id}><b>{invoice.number} · {invoice.partner}</b><span>fällig {new Date(invoice.due).toLocaleDateString('de-DE')}</span></a>)}</article><article className="panel"><h2>Wetter am Montageort</h2><p className="muted">Schnittstelle vorbereitet: Montageorte werden aus Projektadressen gelesen und können an einen Wetteranbieter übergeben werden.</p>{work.installations.map(project=>{const check=materialCheckForProject(project.id,state.materialChecks);return <div className="alertRow" key={project.id}><b>{project.customer}</b><span>{project.projectAddress.city||'Ort offen'} · Material {check.complete?'vollständig':'fehlt'}</span></div>})}</article></section></Shell>;
}
